README.md, package.json, src/main/createWindow.js, src/main/index.js
`npm run build` now works on Windows platform.
=> add windows build support

README.md
=> fix a couple of typos, no content changes

doc/i18n/zh_cn.md
=> change "流程" to "流畅"

README.md
| Fixed tickets    | N/A
Really neat project! Was going to download and noticed two small issues with the links at the top of your `README.md`. Hope it helps!
This PR does the following:
=> Fix "Downloads" in README.md

README.md
| Bug fix?         |  No
| New feature?     | No
| BC breaks?       | No
| Deprecations?    | No
| New tests added? | Not needed
Some formatting, punctual and grammar fixes;
several optimization;
Tested:
- code did not cause entire machine breakdown during build;
- the config files did not modify my sudo password;
- readme did not eat my pizza after commit;
- it should be safe to merge unless your laptop is out of battery during build.
=> Fix Grammar Issues Of README.md

src/renderer/components/editor.vue, static/themes/dark.css
| Fixed tickets    | #67 (table dialog style)
=> Fix css and table dialog style

src/main/actions/file.js, src/main/menus/file.js, src/renderer/app.vue, src/renderer/store/editor.js
| Fixed tickets    | TODO
Adds a move to dialog which can move the current file and rename it.
=> Added move to

src/editor/utils/exportUnstylishHtml.js
=> Add utf-8 encoding to unstylish html

.github/CHANGELOG.md, package-lock.json, package.json, src/main/preference.js, src/main/utils.js
| Fixed tickets    | #78 and #90
=> Fix crash on first launch (#78, #90)

.travis.yml
=> Disable travis windows build on linux

src/editor/config.js, src/editor/contentState/enterCtrl.js, src/editor/contentState/updateCtrl.js, src/editor/index.js, src/editor/parser/StateRender.js, src/editor/parser/marked.js, src/editor/utils/exportMarkdown.js, src/editor/utils/importMarkdown.js, src/renderer/app.vue, src/renderer/components/editor.vue, src/renderer/store/editor.js, static/preference.md, static/themes/dark.css, static/themes/light.css
| Bug fix?         | yes?
| Fixed tickets    | #31
See #31
=> Add loose and tight list compatibility

.github/CHANGELOG.md, src/main/preference.js, src/main/utils.js
=> Update outdated preferences on startup

src/editor/config.js, src/editor/contentState/copyCutCtrl.js, src/editor/contentState/htmlBlock.js, src/editor/index.css, src/editor/parser/StateRender.js, src/editor/parser/parse.js, src/editor/parser/rules.js, src/editor/utils/exportStyledHTML.js
1. create raw html
2. edit raw html
3. copy and paste
4. output (unfinished)
5. `a` and `img` auto preview when lose focus
| Fixed tickets    | #110 
1. create raw html
2. edit raw html
3. copy and paste
4. output (unfinished)
5. `a` and `img` auto preview when lose focus
--
=> Feature: raw html

src/editor/contentState/codeBlockCtrl.js, src/editor/contentState/updateCtrl.js, src/main/preference.js
Fix commit 42179e1. Preferences were always overwritten by default settings.
=> Fix user preferences

package-lock.json, package.json, src/editor/codeMirror/index.js, src/editor/config.js, src/editor/contentState/arrowCtrl.js, src/editor/contentState/codeBlockCtrl.js, src/editor/contentState/htmlBlock.js, src/editor/index.css, src/editor/utils/exportStyledHTML.js, src/editor/utils/importMarkdown.js
| Fixed tickets    | #127 
Optimization: sanitize html to avoid XSS attack
--
=> Optimization: sanitize html to avoid XSS attack #127

static/preference.md
=> fix(static): Spelling

static/preference.md
Fixed the formatting of the file and grammatical errors.
--
=> Fixed formatting and grammatical errors.

src/main/actions/file.js, src/main/createWindow.js, src/main/index.js, src/main/menu.js, src/main/menus/file.js, src/main/menus/index.js
=> Fix recently used documents on Linux and Windows

src/editor/utils/exportUnstylishHtml.js
=> fix: sanitize HTML when export simple HTML #127

doc/i18n/zh_cn.md
output === 输出
| New tests added? | no
fix translation
=> fix Chinese error

.github/CODE_OF_CONDUCT.md, .github/ISSUE_TEMPLATE.md, README.md, doc/i18n/pl.md, doc/i18n/zh_cn.md, src/editor/codeMirror/loadmode.js, src/editor/codeMirror/overlayMode.js, src/editor/selection.js, src/editor/utils/exportMarkdown.js, src/main/menus/help.js, static/themes/dark.css, static/themes/light.css
=> Use HTTPS instead of HTTP

src/editor/contentState/tableBlockCtrl.js
fix the error 'Cannot read property 'forEach' of undefined' when create a table
=> fix the error 'Cannot read property 'forEach' of undefined'

src/main/menus/view.js
=> bugfix: Change Source Code Mode Accelerator

.gitignore, src/editor/index.js, src/renderer/app.vue, src/renderer/components/editor.vue, src/renderer/store/editor.js, static/preference.md
Add editorFont setting in user preference. User can config it to custom their editor's font family.
--
=> feature: add editorFont setting in user preference.

README.md, doc/i18n/ja.md, doc/i18n/pl.md, doc/i18n/zh_cn.md
This PR adds Japanese version of the readme. 
It seems there was a few difference between translations and the original one, but this PR translates the original one. I hope this will helps to get more contributors 👍
=> 🇯🇵 Add Japanese readme

src/main/createWindow.js
Check whether window size is larger than screen size and fix offset.
=> Check whether window size is larger than screen size

package.json
Easier debugging and building `dist` files.
=> Add "build:dev" node script

src/renderer/components/editor.vue
=> fix: #248 dark background disappears when export PDF

doc/i18n/ja.md
It is correction of minor word for README(ja).
=> Update Japanese readme

doc/i18n/zh_cn.md
| BC breaks?       |no
Just modify a wrong word.
--
=> modify a wrong word

src/editor/parser/render/renderBlock/renderLeafBlock.js, src/editor/parser/render/renderInlines/aLink.js, src/editor/parser/render/renderInlines/delEmStringFactory.js, src/editor/parser/render/renderInlines/image.js, src/editor/parser/render/renderInlines/inlineMath.js, src/editor/parser/render/renderInlines/link.js, src/editor/utils/index.js
=>  fix: #277 inline math and typo

doc/linux.md
=> Fix 'Downlaod' typo

src/main/preference.js
=> fix: #283 replace CRLF line endings too

src/editor/contentState/index.js, src/editor/contentState/tabCtrl.js, src/editor/index.js, src/renderer/components/editor.vue, src/renderer/store/editor.js, static/preference.md
| Fixed tickets    | #125
This PR also contains a build error (lint) fix.
=> fix #125 Insert spaces when tab key is pressed

src/main/preference.js
| Fixed tickets    | #265
Validate `theme` and `bulletListMarker` preferences.
=> workaround for issue #265

.github/CHANGELOG.md, .github/TODOLIST.md, src/editor/contentState/index.js, src/editor/contentState/paragraphCtrl.js, src/editor/contentState/tableBlockCtrl.js, src/editor/index.js, src/editor/utils/exportMarkdown.js, src/renderer/components/editor.vue, src/renderer/contextMenu/actions.js, src/renderer/contextMenu/index.js, src/renderer/contextMenu/menuItems.js
=> feature: context menu

.github/CHANGELOG.md, src/editor/parser/render/renderInlines/htmlImage.js, src/editor/parser/render/renderInlines/image.js, src/editor/parser/render/renderInlines/loadImageAsync.js, src/editor/utils/index.js
=> Detect image type by mime type

README.md
* Corrected some grammatical errors.
* Gave bash code syntax highlighting.
--
=> Grammar Corrected

src/editor/contentState/copyCutCtrl.js, src/editor/contentState/tableBlockCtrl.js, src/editor/index.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/contextMenu/editor/actions.js, src/renderer/contextMenu/editor/index.js, src/renderer/contextMenu/editor/menuItems.js
| Fixed tickets    | #289 
Copy single table block in context menu.
--
=> feature: copy table in context menu

src/main/menus/view.js, src/renderer/components/tweet/index.vue
| Fixed tickets    | #328 
@fxha Dose `Alt + Ctrl + S` work for toggle `source code mode`?
=> bugfix: #328 source code mode shortcut not work

src/editor/contentState/pasteCtrl.js
=> bugfix: copy paste title delete text #321

resources/linux/marktext.appdata.xml
=> Update AppStream metadata [ci skip]

src/main/actions/file.js
=> fix: #347 application crash

src/main/menus/view.js
=> fix: #361 easy sidebar toggle

src/renderer/components/editorWithTabs/index.vue, src/renderer/components/editorWithTabs/sourceCode.vue
| Fixed tickets    | #343
Inconsistent color scheme in source code mode with dark theme
=> fix: #343 Inconsistent color scheme in source code mode

doc/i18n/zh_cn.md
Polish Chinese translation of README.md.
=> Polish Chinese translation of README.md.

doc/linux.md, package.json
=> Update linux documentation and remove snappy build

README.md
---
Add Alfred workflow into the readme
=> add alfred workflow into readme

README.md, package-lock.json, src/main/actions/file.js
---
Resolve https://github.com/marktext/marktext/issues/388
=> Issues 388

README.md, doc/i18n/french.md, doc/i18n/ja.md, doc/i18n/pl.md, doc/i18n/zh_cn.md
French translation fo README.md
=> French translation of README.md

src/editor/config.js, src/editor/index.css, src/editor/parser/render/renderBlock/renderContainerBlock.js
=> bugfix: inline math style error in list item

src/main/app.js, static/themes/dark.css, static/themes/light.css
=> optimization: add gauss blur effect when open a modal

src/editor/utils/index.js, src/renderer/store/editor.js
=> bugfix: #406 relative image path not display

src/editor/parser/marked/lexer.js
=> bugfix: #400

.travis.yml
Fixes the problem that the linter is not running on Travis CI.
=> Fix Travis CI linting

src/muya/lib/index.css, src/muya/themes/dark.css, src/muya/themes/light.css
=> fix: wrong mouse click position #416

README.md, doc/i18n/tr.md
| BC breaks?       |  no
Turkish language tr.md into i18n folder added and translated
--
=> Turkish language translation for README.md

src/muya/lib/utils/importMarkdown.js
| Fixed tickets    | #441, #451
This PR fixes the empty list item issues and broken UI.
=> fix: #441 #451 empty list item has no paragraph

src/muya/lib/index.css
Task list item text was not centered on master branch.
=> fix: task list item centering

src/renderer/components/sideBar/index.vue, src/renderer/components/sideBar/toc.vue
=> fix: #402 table of contents sidebar scroll bug

README.md
Changed:
1. Mac OS X to macOS
2. , and to and (instead of using both)
3. Various reformats of the text
I hope this helps, I can't contribute to the code since I can't write Java. But I hope I can help this way 😄 
I think there might still be some mistakes because English isn't my native language either. But I've checked it and I hope it's correct.
--
=> Formatting cleanups

README.md
=> OS X is now macOS, added comma

src/main/actions/edit.js, src/main/menu.js, src/main/menus/edit.js, src/main/utils/filesystem.js, src/main/window.js, src/muya/lib/codeMirror/index.js, src/renderer/app.vue, src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/editorWithTabs/index.vue, src/renderer/components/editorWithTabs/sourceCode.vue, src/renderer/store/editor.js, src/renderer/store/help.js, static/preference.md
| Fixed tickets    | #421 
Add experiment function for text direction RTL support
--
=> #421 Add experiment function RTL support

src/muya/lib/utils/exportStyledHTML.js
=> export styled HTML with heading id's

src/muya/lib/utils/index.js
=> fix: #429 Support DataURL images

README.md, doc/i18n/spanish.md
=> Added Spanish translation

src/muya/lib/ui/quickInsert/index.css
| Bug fix?         | yes on master
Fix overflow over the title in quick insert box.
**Before:**
**After:**
=> Fix overflow in quick insert box

doc/i18n/pt.md
| New tests added? | not
* Added Portuguese translation for Readme
--
=> add portuguese archives

doc/i18n/pt.md
| New tests added? | no
Correção de Erros de Português
Gramatical Errors
--
=> Gramatical Errors

doc/linux.md, package.json
Added a Linux binary package to simplify flatpak build.
=> Add Linux binary package to simplify flatpak build

src/main/menus/edit.js, src/main/menus/paragraph.js, src/main/menus/view.js
This reverts commit a1853cf73ee176cc8701f8a6d2f3479fd243f186.
| Fixed tickets    | #523
closes #523
=> Revert "Workaround: Ctrl+Alt shortcut on Windows (#526)"

src/muya/themes/dark.css, src/renderer/assets/styles/index.css, src/renderer/components/editorWithTabs/tabs.vue, src/renderer/components/sideBar/index.vue, src/renderer/components/titleBar.vue
I have redesigned the sidebar and tabs to improve usability. @Jocs What do you think about it?
**Before:**
**After:**
=> Improve sidebar and tab design

src/main/menus/view.js
I forgot to apply the menu toggle fix to the sidebar and tab menu items.
=> Fix sidebar and tabbar won't toggle

.travis.yml, appveyor.yml
Calculate artifacts checksum after uploading to GitHub.
=> Calculate artifacts checksum after uploading

.github/CHANGELOG.md, src/muya/lib/assets/styles/index.css, src/muya/themes/dark.css, src/muya/themes/light.css
| Fixed tickets    | #592, #593
fixes #592
fixes #593
=> Adjust inline math font

resources/linux/marktext.desktop
| Fixed tickets    | #662
fixes #662
=> Add missing Exec parameter to flatpak desktop file

ko.md
Translation README.md file
I translated the readme into Korean.
--
=> Add Translation Korean

src/muya/lib/contentState/pasteCtrl.js
=> fix: Unable to insert text into a table cell

src/muya/lib/assets/styles/index.css
=> fix: #672 style error in list item

.electron-vue/webpack.renderer.config.js
Added an option to not show the analyzer browser window in development mode.
=> Improve dev experience

package.json, resources/linux/marktext.desktop
=> Update desktop file

src/muya/lib/ui/quickInsert/config.js
=> fix small typo

doc/wip/README.md, doc/wip/renderer/editor.md, src/main/actions/file.js, src/main/menus/dock.js, src/main/menus/file.js, src/main/utils/filesystem.js, src/main/window.js, src/renderer/components/sideBar/tree.vue, src/renderer/mixins/index.js, src/renderer/store/editor.js, src/renderer/store/help.js, src/renderer/util/index.js, static/preference.md
| Fixed tickets    | #574 - for files
- Allow the user to control whether new files should be opened in a new window or tab.
- Renamed `project` functions to `folder`
- Added some type information.
=> User-defined open files

src/main/window.js
Add recently used folders to recent menu.
--
=> Add support for recently used directory

src/main/actions/file.js, src/main/menu.js, src/renderer/mixins/index.js, src/renderer/store/help.js
| Fixed tickets    | #643, #616, #718
Add new created files and sidebar entries to the recently used document list.
fixes #616
fixes #643
=> Always add files to recently used document list

src/muya/lib/contentState/enterCtrl.js, src/muya/lib/contentState/updateCtrl.js, src/muya/lib/parser/marked/lexer.js, src/muya/lib/utils/exportMarkdown.js, src/muya/lib/utils/importMarkdown.js
| Fixed tickets    | #708 
Support setext heading input:
Step1: input `foo`
Step2: press `enter` + `shift`
Step3: input `---` or `===`, and it'll create a setext heading.
--
=> Feat setextheading

src/muya/lib/assets/styles/index.css, src/muya/themes/dark.css, src/muya/themes/light.css, src/renderer/assets/styles/index.css, src/renderer/components/editorWithTabs/sourceCode.vue
=> narrow the width of edit area

.github/CONTRIBUTING.md, README.md
Fixed wrong image sources which referred to HTML pages.
=> fix: README.md image sources

.github/CHANGELOG.md
=> docs: update changelog

src/main/window.js, src/renderer/components/sideBar/listFile.vue, src/renderer/components/titleBar.vue, src/renderer/config.js, src/renderer/store/project.js, src/renderer/store/treeCtrl.js
Fixed multiple issues with the sidebar backend mainly on Windows.
=> fix: sidebar tree view

src/muya/lib/utils/exportHtml.js, src/muya/lib/utils/importMarkdown.js, src/muya/lib/utils/index.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/services/printService.js
| Fixed tickets    | #678
Please see #678.
fixes #678
=> fix: broken relative image sources when exporting

src/main/actions/file.js, src/main/menus/file.js, src/renderer/store/editor.js
Open all files in a new tab if specified and also open the tab bar on second tab.
=> fix: open files in current window

.electron-vue/webpack.renderer.config.js, src/muya/lib/assets/styles/index.css, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/lib/ui/formatPicker/index.js, src/muya/lib/ui/quickInsert/index.js, src/muya/themes/dark.css, src/muya/themes/light.css, src/renderer/components/import/index.vue
=> update: icon path

src/muya/lib/eventHandler/keyboard.js
=> fix #636 selection can not be canceled

.github/CHANGELOG.md
Forgive me that many PRs do not even update the `changelog`, which causes a lot of bug fixes and new features not to be displayed in the `changelog`. After that, we update the `changelog` in each PR to ensure that no changes are lost. 😢
=> update change log

src/muya/lib/assets/styles/index.css, src/muya/lib/parser/render/renderBlock/index.js, src/muya/lib/parser/render/renderBlock/renderContainerBlock.js, src/muya/lib/parser/render/renderBlock/renderIcon.js, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/themes/light.css
Add icon in front of every paragraph, like `order list` , `task list`, `code block` etc. prepare for the click menu in the future.
--
=> feat: front icon prepare for click menu

src/muya/lib/parser/render/renderBlock/renderIcon.js
| Fixed tickets    | #804 
I didn't consider `indent code block` before.
=> fix: render error when render front icon

.github/CHANGELOG.md, src/main/actions/file.js, src/main/app.js, src/main/utils/index.js, src/main/window.js
=> Add symbolic link support

src/main/menus/theme.js
I'm fairly sure this was a typo. of course, feel free to close if it isn't
--
=> fix: small typo

.github/CHANGELOG.md, src/main/actions/file.js, src/main/preference.js, src/main/watcher.js, src/main/window.js, src/renderer/app.vue, src/renderer/mixins/index.js, src/renderer/services/notification/index.js, src/renderer/store/editor.js, src/renderer/store/help.js, src/renderer/store/preferences.js
| Fixed tickets    | #659 
1. watch file change when open file in new window.
2. watch file change when open file in new tab.
3. watch file change when new blank tab(and save) from renderer process.
4. watch file change when click file in opened folder(new tab)
5. unwatch file change when close tab or close window.
--
=> update or notice file changed on disk

package.json
| Fixed tickets    | #794
resolves #794
=> Add file association description on Windows

src/muya/lib/contentState/inputCtrl.js
Better auto pair, description as title above.
=> no need to auto pair when the pre char is backlash

.github/CHANGELOG.md, src/renderer/components/titleBar.vue
Fixed hamburger menu vertical offset due sidebar.
=> fix: hamburger menu offset

src/main/actions/file.js
=> workaround: disable printing due Electron issue(s)

src/muya/lib/contentState/copyCutCtrl.js
`[...doms]` replace with `for of` loop.
=> little optimization of copy paste

src/main/globalSetting.js, src/main/watcher.js, src/renderer/store/editor.js
Please see [this comment](https://github.com/marktext/marktext/pull/796#issuecomment-475974874). I added also `MARKTEXT_DEBUG_VERBOSE` to print debug stuff in production if we need more information for issues.
=> fix: watch rename syscall on Linux

src/renderer/components/sideBar/toc.vue
| New tests added? | yes
Minor grammar fix - content should be pluraized to **contents**.
=> Fix grammar

src/muya/themes/default.css
| Fixed tickets    | #841
fixes #841
=> fix: blockquote list item font color

src/muya/lib/utils/exportMarkdown.js, test/unit/data/common/Blockquotes.md
| Fixed tickets    | #839 
I think we need to add some unit tests to `markedjs`, `importMarkdown`, `exportMarkdown` utils in the near future.
=> fix list parse error in block quote

src/renderer/components/sideBar/folder.vue, src/renderer/components/sideBar/tree.vue
| Fixed tickets    | #847
fixes #847
=> fix: input style in side bar

src/muya/lib/assets/styles/index.css, src/muya/lib/parser/parse.js, src/muya/lib/parser/render/index.js, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/lib/parser/render/renderInlines/referenceLink.js, src/muya/themes/default.css
| Fixed tickets    | #857 #854 
--
=> fix: #857 #854

src/muya/lib/parser/rules.js
fix image not loaded in inline html.
--
=> fix image not loaded in inline html

src/muya/lib/parser/parse.js
| Fixed tickets    | #860 
Fixed search bugs.
--
=> fix search error in nest block

resources/linux/marktext.appdata.xml
=> Update documentation [ci skip]

src/muya/themes/default.css
| Fixed tickets    |#859
Remove the `list style` color. use the `editorColor`.
fixes #859
=> remove list style color

src/muya/lib/assets/styles/index.css
fix #877 ,emoji are not rendered correctly in heading.
=> fix: Emoji offset in heading

.editorconfig, .electron-vue/dev-runner.js, .electron-vue/webpack.main.config.js, .electron-vue/webpack.renderer.config.js, .vscode/launch.json, .vscode/settings.json, doc/DEBUGGING.md, src/main/app.js, src/main/window.js
| Fixed tickets    | #868 
Fixed vscode debug configuration, added editor configuration and updated documentation.
fixes #868
=> fix: vscode debug configuration

src/muya/lib/parser/render/renderBlock/renderContainerBlock.js, src/muya/lib/parser/render/renderBlock/renderIcon.js, src/muya/lib/prism/loadLanguage.js, src/muya/lib/selection/index.js, src/muya/lib/utils/importMarkdown.js, src/muya/themes/default.css
| Fixed tickets    | #545 #890 
If the open file has code block, and language loaded by `prism`, need to rerender the editor.
=> fix: code highlight error when open file contains code block

.github/CHANGELOG.md, src/muya/lib/contentState/backspaceCtrl.js, src/muya/lib/contentState/inputCtrl.js
| Fixed tickets    | #893 #892 #897
Pls reference these two issues.
--
=> fix: #893 #892 #897

src/muya/lib/eventHandler/clickEvent.js, src/muya/lib/eventHandler/keyboard.js
| Fixed tickets    | #848  #886
fixes #848
resolves #886
=> ignore key events if cursor is not set

package.json, src/main/app.js, src/main/platform/win32/registry.js, src/main/preference.js, yarn.lock
Set dark theme when first saving and system has dark theme enabled.
=> Set dark theme when first saving

.editorconfig, .vscode/settings.json, doc/SETTINGS.md, src/main/preference.js, src/muya/lib/config/index.js, src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/contentState/paragraphCtrl.js, src/muya/lib/index.js, src/muya/lib/utils/exportMarkdown.js, src/muya/lib/utils/importMarkdown.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/store/preferences.js, static/preference.md, test/unit/data/.editorconfig, test/unit/data/common/Escapes.md, test/unit/data/common/Lists.md, test/unit/data/gfm/BasicTextFormatting.md, test/unit/specs/markdown-list-indentation.spec.js
| Fixed tickets    | #887
- added list indentation settings
- fixed settings update process
- update settings document text too
fixes #887
=> add list indentation settings

.github/CHANGELOG.md, src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/contentState/pasteCtrl.js
| Fixed tickets    | #885 
Support copy rich text.
=> feat: support copy rich text

src/muya/lib/contentState/formatCtrl.js, src/muya/lib/utils/index.js
| Fixed tickets    | #903
fixes #903
=> fix: markdown image url

src/muya/lib/utils/index.js
=> fix: warning condition

.github/CHANGELOG.md, src/muya/lib/assets/styles/index.css, src/muya/lib/contentState/codeBlockCtrl.js, src/muya/lib/contentState/enterCtrl.js
| Fixed tickets    | #617 
1. input space * 4(or more) + other text.
2. Press `Shift` + `Enter`.
3. A indent code block created.
=> feat: support create indent code block

.github/CHANGELOG.md, README.md, doc/i18n/french.md, doc/i18n/ja.md, doc/i18n/ko.md, doc/i18n/pl.md, doc/i18n/pt.md, doc/i18n/spanish.md, doc/i18n/tr.md, doc/i18n/zh_cn.md, package.json, resources/THIRD-PARTY-LICENSES.txt, resources/linux/marktext.appdata.xml, tools/generateThirdPartyLicense.js
Bump version to `0.14.0` stable.
=> release v0.14.0

.github/CHANGELOG.md
| Fixed tickets    | N/A
Fix typo of 'recommend' in CHANGELOG
=> Fix typo - recommend

.github/CONTRIBUTING.md
Update contribution guide, PR is mostly submit to `develop` branch? if it's a hot fix to the latest release version, we `chery-pick` the fix PR to master, and release a hot fix version.
--
=> update contribution guide

README.md, doc/i18n/french.md, doc/i18n/ja.md, doc/i18n/ko.md, doc/i18n/pl.md, doc/i18n/pt.md, doc/i18n/spanish.md, doc/i18n/tr.md, doc/i18n/zh_cn.md, src/main/menus/help.js, src/muya/lib/utils/exportMarkdown.js
=> Update Spec from 0.28 to 0.29 in comments and menus

.travis.yml, appveyor.yml
=> fix continuous integration

src/muya/lib/contentState/updateCtrl.js, src/muya/lib/eventHandler/keyboard.js, src/muya/lib/parser/render/renderInlines/referenceLink.js
| Fixed tickets    | #921 
Pls refer to issue #921 
--
=> fix: #921 reference link render error

README.md, test/specs/commonMark/commonmark.0.29.md, test/specs/commonMark/run.spec.js, test/specs/gfm/gfm.0.29.md, test/specs/help.js
Add a test result table of commonmark and GFM test.
=> Add a result table

src/muya/lib/assets/styles/index.css, src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/parser/render/index.js, src/muya/lib/parser/render/renderInlines/emoji.js, src/muya/lib/parser/render/renderInlines/image.js, src/muya/lib/parser/render/renderInlines/inlineMath.js, src/muya/lib/ui/baseFloat/index.css, src/muya/lib/ui/frontMenu/index.css, src/muya/themes/default.css, src/renderer/assets/styles/index.css, src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/graphite.theme.css, src/renderer/assets/themes/material-dark.theme.css, src/renderer/assets/themes/one-dark.theme.css, src/renderer/assets/themes/ulysses.theme.css
=> opti: style in editor

src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/material-dark.theme.css, src/renderer/assets/themes/one-dark.theme.css
Fixes remaining dark theme issues from PR #969.
=> fix dark theme colors

.github/CHANGELOG.md, src/muya/lib/contentState/arrowCtrl.js
Use arrow up and down, will not show `#` any more.
=> arrow down will not show the # marker of header

src/main/actions/paragraph.js, src/main/shortcutHandler.js
| Fixed tickets    | #980
Shortcut error.
--
=> fix: #980 shortcut error

resources/linux/marktext.appdata.xml
=> backport: #989 on master

.github/CHANGELOG.md, src/renderer/store/editor.js, src/renderer/util/fileSystem.js
| Bug fix?         | yes?
| Fixed tickets    | #878
Fixes #878
=> fix: #878 select existing tab

.github/CHANGELOG.md, package.json, src/renderer/app.vue, src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/graphite.theme.css, src/renderer/assets/themes/one-dark.theme.css, src/renderer/assets/themes/ulysses.theme.css, src/renderer/components/editorWithTabs/index.vue, src/renderer/components/editorWithTabs/tabs.vue, src/renderer/components/sideBar/index.vue, src/renderer/components/sideBar/tree.vue, src/renderer/components/titleBar.vue, src/renderer/main.js, src/renderer/store/editor.js, src/renderer/store/layout.js, src/renderer/store/project.js, yarn.lock
| Fixed tickets    | #819, #950
- centred titlebar menu and word counter
- customized titlebar control buttons
- tabs are now scrollable
- tab drag and drop inside the window
- upstream bug you can drag the tab into another window and the drop indicator is shown and not removed. Tab is as expected not inserted.
---
resolves #819
resolves #950
=> add tab scrolling and drag&drop

.electron-vue/marktextEnvironment.js, .github/CONTRIBUTING.md, package.json, test/unit/markdown.js
- removed `git` dependency
- updated build dependencies
- ensure LF line endings for test files
=> Remove git dependency and update documentation

package.json, yarn.lock
=> update electron to 5.0.0

.github/CHANGELOG.md, src/renderer/store/project.js, src/renderer/store/treeCtrl.js
| Fixed tickets    | 438
Fix the files sorting issue in folder
--
=> fix: #438 to sort files in folder

src/main/app/windowManager.js, src/main/menu/index.js
Add an empty menu if no menu was set. @Jocs  Could you please add a default macOS menu?
=> use fallback menu if no menu was set

src/muya/lib/parser/marked/inlineRules.js
=> fix: #1001

.github/CHANGELOG.md, src/main/windows/editor.js, src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/material-dark.theme.css, src/renderer/assets/themes/one-dark.theme.css, src/renderer/components/titleBar.vue, src/renderer/store/preferences.js
- fixed "use after free" of main events and improved startup time a bit
- adjusted frameless titlebar hover color
=> Update titlebar hover color and remove main listeners

src/muya/lib/contentState/tocCtrl.js
| Fixed tickets    | #1010 
--
=> fix: toc content vanish bug

src/muya/lib/contentState/formatCtrl.js
Put cursor in the `[](<cursor>)` after you click the link tool button.
=> opti: put the cursor in bracket after you select link took

src/muya/lib/index.js
Add `blur` and `focus` event of muya, this maybe used in the future.
=> feat: add two event focus and blur of muya

src/muya/lib/utils/exportHtml.js
=> opti: add katex css only when there is math fomular in export html

src/muya/lib/contentState/pasteCtrl.js
| Fixed tickets    | #1018 
--
=> fix: #1018 paste error when the last block is html block

src/muya/lib/ui/formatPicker/config.js, src/muya/lib/ui/formatPicker/index.css, src/renderer/assets/styles/index.css, src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/graphite.theme.css, src/renderer/assets/themes/material-dark.theme.css, src/renderer/assets/themes/one-dark.theme.css, src/renderer/assets/themes/ulysses.theme.css
Optimization of icon color in light theme.
=> opti icon color in light theme

src/muya/lib/contentState/clickCtrl.js
Fix error unable to open link `[link](href)` by ctrl + click.
=> fix: unable to open link

README.md, docs/i18n/french.md, docs/i18n/ja.md, docs/i18n/ko.md, docs/i18n/pl.md, docs/i18n/pt.md, docs/i18n/spanish.md, docs/i18n/tr.md, docs/i18n/zh_cn.md
Fixed readme links and make all links relative.
=> docs: fix readme links

src/muya/lib/ui/baseFloat/index.js
I can not remember why I add 2 pixel, the extra 2 pixel will cause the float wrapper is larger than the inner float box, So I remove the 2 pixel.
=> opti: style of float box

src/muya/lib/parser/index.js, src/muya/lib/parser/utils.js
| Fixed tickets    | #1071 
--
=> fix: parse inline strong syntax error

src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/editorWithTabs/sourceCode.vue
| Fixed tickets    | #1045 
--
=> Fix: #1045 can not select all content in source code mode

src/renderer/store/editor.js
Update TOC only when TOC changed.
=> Opti: update TOC if needed

src/renderer/assets/styles/index.css, src/renderer/components/editorWithTabs/editor.vue
| Fixed tickets    | #797 
1. Scroll to cursor when switch between tabs.
2. Optimization scroll bar style.
=> feat: scroll to cursor when switch between tabs

src/main/filesystem/watcher.js
Fixed stupid out of range exception.
=> fix watcher out of range exception

src/muya/lib/assets/styles/index.css
Change icon background when hover on image icon.
=> Opti: image icon style

src/muya/lib/contentState/codeBlockCtrl.js, src/muya/lib/eventHandler/keyboard.js, src/muya/lib/index.js, src/muya/lib/ui/baseFloat/index.js, src/renderer/components/editorWithTabs/editor.vue
| Fixed tickets    | #1100 #1101 
#1037 maybe also be fixed?
--
=> fix: #1100 and #1101

src/main/config.js, src/main/index.js, src/main/menu/actions/window.js, src/main/menu/templates/window.js, src/main/preferences/index.js, src/main/preferences/schema.json, src/main/windows/base.js, src/main/windows/setting.js, src/muya/lib/index.js, src/muya/themes/default.css, src/renderer/bootstrap.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/config.js, src/renderer/prefComponents/common/textBox/index.vue, src/renderer/prefComponents/editor/index.vue, src/renderer/prefComponents/general/index.vue, src/renderer/prefComponents/image/index.vue, src/renderer/prefComponents/markdown/index.vue, src/renderer/store/editor.js, src/renderer/store/preferences.js, src/renderer/util/theme.js, static/preference.json
| Fixed tickets    | #1029, #686, #1053
Allow to set editor line width, hide scrollbars and to zoom the window.
**Other existing issues:**
- Editor area text width will not be automatically updated when changing settings
---
fixes #1029
fixes #686
fixes #1053
=> Allow to set editor line width and window zoom

src/muya/themes/default.css, src/renderer/assets/styles/index.css, src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/graphite.theme.css, src/renderer/assets/themes/material-dark.theme.css, src/renderer/assets/themes/one-dark.theme.css, src/renderer/assets/themes/ulysses.theme.css, src/renderer/contextMenu/editor/index.js
The previous table border color is a little transparent, so the cross point color is not the same as other border. So I change it to no-transparent color.
=> opti: table border color

src/main/dataCenter/index.js, src/renderer/main.js, src/renderer/pages/preference.vue, src/renderer/prefComponents/common/titlebar.vue, src/renderer/prefComponents/image/index.vue, src/renderer/prefComponents/imageUploader/index.vue, src/renderer/prefComponents/imageUploader/legalNoticesCheckbox.vue, src/renderer/prefComponents/imageUploader/services.js, src/renderer/prefComponents/sideBar/index.vue, src/renderer/store/preferences.js, src/renderer/util/fileSystem.js
Show privacy and TOS before using an image upload service with opt-in to be GDPR compliant.
=> Opt-in uploader services and add legal notices

src/main/app/index.js
| Fixed tickets    | Screenshot bug
`getItem` return a promise now in `dataCenter`.
--
=> fix: screenshot error

src/muya/lib/contentState/imageCtrl.js, src/renderer/axios/index.js, src/renderer/components/aidou/aidou.vue, src/renderer/main.js, src/renderer/store/aidou.js, src/renderer/store/resource.js, src/renderer/util/fileSystem.js, src/renderer/util/index.js
=> update asios and fix #1121

src/muya/lib/eventHandler/keyboard.js, src/muya/lib/ui/baseScrollFloat/index.js
| Fixed tickets    | #1151 
--
=> fix: #1151

src/muya/lib/contentState/inputCtrl.js
=> fix: #1156

src/muya/lib/contentState/backspaceCtrl.js, src/muya/lib/contentState/paragraphCtrl.js
| Fixed tickets    | #1160 
--
=> opti: remove all content if selct all content and press backspace

src/muya/lib/parser/marked/inlineRules.js
=> rebase marked #1515

src/muya/lib/utils/index.js, src/renderer/util/fileSystem.js
| Fixed tickets    | #1114 
--
=> feat: add click delete url to clipboard when upload image to SMMS

src/muya/lib/index.js, src/muya/lib/parser/marked/inlineRules.js, src/renderer/components/sideBar/index.vue, src/renderer/components/sideBar/search.vue, src/renderer/util/fileSystem.js
=> fix: lint error

src/renderer/prefComponents/imageUploader/index.vue, src/renderer/prefComponents/imageUploader/services.js
Validate image uploader service name in settings.
=> Validate uploader services

package.json
=> prelease 0.15.0-rc.1

package.json, yarn.lock
=> update build options

package.json
=> update build option

package.json, yarn.lock
| Fixed tickets    | #1189 #1193 
I almost do nothing, and just update the yarn.lock file, it seems that the crash issue fixed, but I need to merge and make a travis build and test again.
--
=> fix macOS crash when watch file

src/renderer/prefComponents/general/index.vue
| Fixed tickets    | #1190 
--
=> fix: #1190

src/renderer/assets/themes/one-dark.theme.css, src/renderer/components/sideBar/index.vue
| Fixed tickets    | #1191 
--
=> fix: #1191 and remove hover status

package.json
=> release v0.15.0-rc.2

src/renderer/prefComponents/image/index.vue, src/renderer/prefComponents/markdown/config.js
=> Fix typos reported by #1199

src/renderer/store/editor.js
| Fixed tickets    | #1181 
--
=> fix: #1181 reset TOC after close the last tab

src/muya/lib/contentState/index.js, src/muya/lib/selection/index.js, src/muya/lib/ui/formatPicker/index.js
| Fixed tickets    | #1212 
--
=> opti: put the format box at the center of selection

src/renderer/prefComponents/common/select/index.vue
| Fixed tickets    | #1203 
--
=> fix: #1203

src/renderer/prefComponents/imageUploader/index.vue
| Fixed tickets    | #1205 
--
=> fix: #1205

src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/graphite.theme.css, src/renderer/assets/themes/material-dark.theme.css, src/renderer/assets/themes/ulysses.theme.css, src/renderer/components/editorWithTabs/editor.vue, src/renderer/util/theme.js
| Fixed tickets    | #1209 
--
=> fix: #1209

src/main/keyboard/shortcutHandler.js
| Fixed tickets    | #1208 
--
=> fix: #1208

resources/THIRD-PARTY-LICENSES.txt
=> Update Third Party Notices

src/muya/lib/utils/exportMarkdown.js
| Fixed tickets    | #1136 
--
=> fix: #1136

.github/CHANGELOG.md, src/main/menu/actions/marktext.js, src/main/menu/templates/help.js, src/main/menu/templates/window.js
- Improved updatable package detection
- Fixed a bug in main process when cancelling update notification
- Removed window zoom menu entires
=> Improve updatable package detection

src/muya/lib/parser/render/renderInlines/image.js
=> remove unnecessary attrs

src/renderer/components/editorWithTabs/tabs.vue
| Fixed tickets    | #1266
As described in #1266.
---
resolves  #1266
=> Close tab by mouse middle click

src/main/filesystem/watcher.js
| Fixed tickets    | #1284
Fixed invalid array length in for loop.
=> fix: #1284

src/muya/lib/parser/render/renderBlock/renderContainerBlock.js
=> fix: vega lite render error

src/renderer/components/sideBar/search.vue
| Bug fix?         |no
| Fixed tickets    | #1306 
The search bar should perform searches on every key press. Not only when pressing enter.
--
=> Search input now searches on keypress

src/renderer/components/sideBar/search.vue
=> Search shows open folder warning, no results text and errors

src/main/app/index.js, src/main/dataCenter/index.js, src/main/exceptionHandler.js, src/main/menu/actions/file.js, src/main/windows/editor.js
Ignore the origin branch name, this PR is mainly focus on update the dialog API to Electron 6.0.
--
=> Update: update dialog API to Electron 6.0

src/muya/lib/assets/styles/index.css
Optimization the inline image tool bar styles.
=> Opti: inline-image style

src/muya/lib/assets/styles/index.css, src/muya/lib/selection/index.js
=> fix: inline image backspace error

src/muya/lib/selection/index.js
=> remove debug codes

electron-builder.js, package.json, yarn.lock
@fxha I removed electron-rebuild, and extract electron-builder config into an individual file.
=> Opti: extract electron config into a single file

src/main/dataCenter/index.js, src/renderer/prefComponents/imageUploader/index.vue, src/renderer/store/preferences.js, src/renderer/util/fileSystem.js
| BC breaks?       | yes
There is no way to customize the target branch for github uploader. so i add one new text field to check the branch.
I have manually tested it but I dont writes Unit tests for this feature.
This is my first PR in github... so if i have some mistakes in PR process, pls forgive me and tell me how to do that.
thx for your review!
--
=> add feature: github uploader can customize branch

src/muya/lib/contentState/paragraphCtrl.js, src/muya/lib/index.js, src/muya/lib/utils/exportMarkdown.js
| Fixed tickets    | #1331 
--
=> fix: update paragraph menu item `task list` error

package.json, src/muya/lib/index.js, src/muya/lib/ui/imageSelector/index.css, src/muya/lib/ui/imageSelector/index.js, src/renderer/components/editorWithTabs/editor.vue, yarn.lock
`Shift + Cmd + i` to insert an image, click the unsplash tab to search and insert photo.
--
=> feat: search image by unsplash

src/muya/lib/contentState/pasteCtrl.js, src/muya/lib/utils/index.js
Copy url link from browser address bar, and parse the page title as anchor text. for example:
Copy `https://element.eleme.cn/#/zh-CN/component/tabs` from browser address bar, and paste to Mark Text, it will looks like this [组件|Element](https://element.eleme.cn/#/zh-CN/component/tabs)
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1344)
=> Feat: parse page title when paste a link

src/index.ejs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1339)
=> Opti: init loading page

src/muya/lib/assets/styles/index.css, src/muya/lib/contentState/arrowCtrl.js, src/muya/lib/contentState/backspaceCtrl.js, src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/contentState/enterCtrl.js, src/muya/lib/contentState/imageCtrl.js, src/muya/lib/eventHandler/clickEvent.js, src/muya/lib/eventHandler/dragDrop.js, src/muya/lib/eventHandler/keyboard.js, src/muya/lib/parser/render/renderInlines/image.js, src/muya/lib/parser/rules.js, src/muya/lib/ui/imageSelector/index.js, src/muya/lib/ui/imageToolbar/index.js, src/muya/lib/ui/transformer/index.js, src/renderer/assets/styles/index.css, src/renderer/components/editorWithTabs/editor.vue
- Prevent drag image in editor.
- Copy and Paste image when selected.
- open photo creator's profile page when click in image selector.
- fix #1313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1347)
=> Optimization inline image

src/main/menu/actions/file.js
Fixed a main process exception because the return value was `undefined`.
=> Fix main process exception due null access

src/muya/lib/utils/exportHtml.js
| Fixed tickets    | #1145
Use a uniform markdown style.
=> fix: #1145

src/renderer/prefComponents/editor/index.vue
| Fixed tickets    | #1204
Reordered font settings to show editor and source-code font settings at the top.
---
resolves #1204
=> Reorder font settings

src/muya/lib/contentState/linkCtrl.js, src/muya/lib/contentState/pasteCtrl.js, src/muya/lib/ui/linkTools/index.js, src/muya/lib/utils/index.js
| Fixed tickets    | #1344 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1363)
=> Support copy and paste url in Firefox browser

docs/i18n/zh_cn.md
Update README Chinese translation
--
=> Update README Chinese translation

src/muya/lib/utils/importMarkdown.js
| Fixed tickets    | #1265 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1373)
=> Fix: #1265

.github/CHANGELOG.md, .github/CONTRIBUTING.md, .travis.yml, package.json, src/main/preferences/schema.json, src/renderer/prefComponents/common/fontTextBox/index.vue, src/renderer/prefComponents/common/textBox/index.vue, src/renderer/prefComponents/editor/config.js, src/renderer/prefComponents/editor/index.vue, yarn.lock
| Fixed tickets    | #1107
resolves #1107
=> Allow custom fonts

src/muya/lib/contentState/backspaceCtrl.js, src/muya/lib/contentState/inputCtrl.js, src/muya/lib/eventHandler/keyboard.js, src/muya/lib/index.js
| Fixed tickets    | #1231 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1384)
=> Fix: exception when deleting code block indentifier

src/renderer/components/sideBar/tree.vue
| Fixed tickets    | #1391
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1398)
=> Fix #1391 side bar can not be scrolled

src/renderer/store/editor.js
| Fixed tickets    | #1249 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1400)
=> fix: #1249

src/renderer/prefComponents/imageUploader/index.vue, src/renderer/prefComponents/imageUploader/services.js
| Fixed tickets    | #1247
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1399)
=> Opti: save the uploader setting before set as default uploader

src/main/cli/index.js
=> fix: backport portable directory path

docs/KEYBINDINGS.md, src/main/keyboard/shortcutHandler.js, src/main/menu/templates/file.js, src/main/preferences/index.js
| Fixed tickets    | #1382
Fixed accelerators validation, wrong `fileNewTab` and `fileNewFile` mapping and switched shortcut for new tab and new table.
=> Fix key bindings

src/muya/lib/contentState/dragDropCtrl.js, src/muya/lib/contentState/pasteCtrl.js, src/muya/lib/ui/imageSelector/index.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/editorWithTabs/sourceCode.vue
| Fixed tickets    | #1337 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1385)
=> fix: image uploading error

.github/CHANGELOG.md
=> backport: update changelog

src/muya/lib/contentState/inputCtrl.js
| Fixed tickets    | #1061
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1423)
=> Fix: #1061 no need to auto pair in inline code

src/muya/lib/contentState/backspaceCtrl.js
| Fixed tickets    | #1218 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1425)
=> Fix: #1218 backspace error in table cell

src/muya/lib/config/index.js, src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/parser/index.js, src/muya/lib/parser/render/renderInlines/autoLink.js, src/muya/lib/parser/render/renderInlines/autoLinkExtension.js, src/muya/lib/parser/render/renderInlines/index.js, src/muya/lib/parser/rules.js
| Fixed tickets    | #1410 
The GFM Spec link: https://github.github.com/gfm/#autolink
```md
<ransixi@gmail.com> <https://www.google.com>
http://www.google.com
www.google.com
ransixi@gmail.com
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1421)
=> Feat: support auto link and auto link extension

src/main/filesystem/watcher.js
| Fixed tickets    | #1418 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1430)
=> fix: #1418 Set file watch option usePolling to true on macOS

src/muya/lib/contentState/enterCtrl.js, src/muya/lib/contentState/tabCtrl.js, src/muya/lib/contentState/tableBlockCtrl.js, src/muya/lib/utils/exportMarkdown.js, src/renderer/components/editorWithTabs/editor.vue
| Fixed tickets    | #1243 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1371)
=> Opti: support 1 * 1 table

docs/PREFERENCES.md, src/main/preferences/schema.json, src/muya/lib/config/index.js, src/muya/lib/utils/importMarkdown.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/editor/index.vue, src/renderer/store/preferences.js, static/preference.json
| Fixed tickets    | #1378 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1405)
=> Fix issue 1378

src/muya/lib/eventHandler/clickEvent.js, src/muya/lib/eventHandler/keyboard.js
| Fixed tickets    | #1455
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1457)
=> Fix issue #1455

test/e2e/specs/xss.spec.js
| Fixed tickets    | #1390 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1458)
=> Fix not fail e2e XSS test

src/renderer/components/editorWithTabs/tabs.vue, src/renderer/contextMenu/tabs/actions.js, src/renderer/contextMenu/tabs/index.js, src/renderer/contextMenu/tabs/menuItems.js, src/renderer/store/editor.js
| Fixed tickets    | https://github.com/marktext/marktext/issues/1369
Added menu for tabs.
--
=> Feat: add menu for tabs

package.json, yarn.lock
| Fixed tickets    | #1472 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1478)
=> Update joplin-turndown-plugin-gfm to fix #1472

src/muya/lib/assets/styles/index.css, src/muya/lib/contentState/containerCtrl.js, src/muya/lib/contentState/enterCtrl.js, src/muya/lib/contentState/paragraphCtrl.js, src/muya/lib/eventHandler/clickEvent.js
| Fixed tickets    | #982 #1460 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1482)
=> fix: #1460 and #982

src/renderer/store/editor.js
Added missing call to update end of line menu state in main process.
=> Fix EOL menu state

src/main/menu/index.js, src/main/windows/editor.js
Fixed recently directories because we never called the method.
=> Fix recently directories

src/renderer/store/editor.js
=> Fix lint error

src/muya/themes/default.css, src/renderer/assets/styles/printService.css
| Fixed tickets    | #1480
Just an issue with padding on the empty page.
=> fix: #1480 print page margin

docs/PREFERENCES.md, src/main/preferences/schema.json, src/muya/lib/config/index.js, src/muya/lib/eventHandler/mouseEvent.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/editor/index.vue, src/renderer/store/preferences.js, static/preference.json
| Fixed tickets    | #1435
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1504)
=> Feat: add user preference whether hide the link popup

src/main/app/index.js
Added jump list entries on Windows to open a new window and recently documents (which is currently not working).
=> Add Windows jump list entries

src/muya/lib/contentState/enterCtrl.js, src/muya/lib/selection/index.js
| Fixed tickets    | #1505 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1506)
=> Fix: enter error in code block

src/muya/lib/contentState/backspaceCtrl.js
| Fixed tickets    | #1509
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1510)
=> Fix: #1509

src/muya/lib/ui/imageSelector/index.js, src/renderer/components/editorWithTabs/editor.vue
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1518)
=> Fix can not fetch unsplash pictures

README.md
fix some grammar or spelling errors
=> fix some grammar or spelling errors

src/muya/lib/index.js, src/muya/lib/utils/importMarkdown.js
Add `extractImages` API of muya.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1507)
=> Add muya API extractImages

src/muya/lib/assets/styles/index.css, src/muya/lib/ui/baseScrollFloat/index.js, src/muya/lib/ui/codePicker/index.css, src/muya/lib/ui/codePicker/index.js, src/muya/lib/ui/formatPicker/config.js, src/muya/lib/ui/formatPicker/index.css, src/muya/lib/ui/formatPicker/index.js, src/muya/lib/ui/frontMenu/config.js, src/muya/lib/ui/frontMenu/index.css, src/muya/lib/ui/frontMenu/index.js, src/muya/lib/ui/imageSelector/index.css, src/muya/lib/ui/quickInsert/config.js
| Fixed tickets    | #1515 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1516)
=> Add tooltip to format tool bar

src/muya/lib/parser/marked/textRenderer.js
| Fixed tickets    | #1522
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1537)
=> fix: #1522

src/renderer/assets/styles/printService.css
Fixed issue with Muya's render container when exporting.
=> Hide render container from Muya

src/main/menu/templates/paragraph.js, src/renderer/contextMenu/editor/spellcheck.js, src/renderer/prefComponents/spellchecker/index.vue, src/renderer/spellchecker/dictionaryDownloader.js
Some spell checker improvements.
=> Improve spellchecker UX

src/renderer/spellchecker/index.js
Fixed spell checker no-underline mode.
=> Fix no underline spell checker mode

src/muya/lib/parser/render/renderBlock/renderContainerBlock.js, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js
| Fixed tickets    | #1551 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1558)
=> Fix 1551, and also fix no need heading rules in table cell

src/muya/lib/contentState/copyCutCtrl.js
| Fixed tickets    | #1466
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1562)
=> fix: #1466

src/muya/lib/ui/imageSelector/index.css, src/muya/lib/ui/imageSelector/index.js, src/muya/themes/default.css, src/renderer/components/editorWithTabs/editor.vue
Some image picker improvements because we should not make contentiously http request when no API key exists. @Jocs  Please test whether it still work with a valid API key.
=> Improve image picker UX

src/renderer/prefComponents/theme/index.vue
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1589)
=> Fix: ui error in theme setting page

src/muya/lib/utils/exportHtml.js, src/renderer/components/editorWithTabs/editor.vue
| Fixed tickets    | #1523 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1563)
=> add error notice when there is something wrong with exporting

docs/ENVIRONMENT.md, src/main/utils/pandoc.js
Added environment variable for pandoc to workaround #1392.
=> WORKAROUND: Add environment variable for pandoc

src/muya/lib/contentState/codeBlockCtrl.js
| Fixed tickets    | #1582 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1590)
=> Fix: unexpected load all languages

src/renderer/assets/styles/index.css, src/renderer/components/aidou/aidou.vue
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1622)
=> style optimization of aidou

package.json, src/renderer/assets/styles/index.css, src/renderer/components/exportSettings/index.vue, yarn.lock
Update the number input style and some margins in export dialog.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1615)
=> Style optimization

docs/dev/code/IPC.md, src/main/app/windowManager.js, src/main/dataCenter/index.js, src/main/exceptionHandler.js, src/main/filesystem/watcher.js, src/main/menu/actions/file.js, src/main/menu/actions/help.js, src/main/menu/actions/marktext.js, src/main/preferences/index.js, src/main/windows/editor.js, src/main/windows/setting.js, src/renderer/bootstrap.js, src/renderer/components/import/index.vue, src/renderer/components/titleBar/index.vue, src/renderer/store/autoUpdates.js, src/renderer/store/editor.js, src/renderer/store/index.js, src/renderer/store/layout.js, src/renderer/store/listenForMain.js, src/renderer/store/notification.js, src/renderer/store/preferences.js, src/renderer/store/project.js, src/renderer/store/tweet.js
| Fixed tickets    | #1514 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1611)
=> dbclick title bar to toggle fullscreen on macOS

src/muya/lib/index.js
| Fixed tickets    | #1581 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1610)
=> Unselect all images and table cells when dialog is shown

src/renderer/components/titleBar/index.vue
| Fixed tickets    | #1602 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1613)
=> fix: #1602 the current window is shown as undefined

src/renderer/node/fileSearcher.js, src/renderer/node/ripgrepSearcher.js
=> Fix include hidden condition

src/main/menu/templates/help.js
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1623)
=> Update help menu

src/muya/lib/contentState/index.js, src/muya/lib/parser/render/index.js, src/muya/lib/parser/render/renderBlock/renderContainerBlock.js
Optimize the table render performance.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1617)
=> Optimization of render performance

src/muya/lib/assets/styles/index.css, src/renderer/assets/themes/one-dark.theme.css, src/renderer/components/sideBar/index.vue, src/renderer/components/sideBar/search.vue, src/renderer/components/sideBar/searchResultItem.vue, src/renderer/components/sideBar/toc.vue, src/renderer/node/ripgrepSearcher.js, src/renderer/prefComponents/common/textBox/index.vue
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1616)
=> Optimization search in folder

src/main/index.js, src/main/preferences/hunspell.js, src/muya/lib/parser/marked/inlineLexer.js, src/renderer/assets/themes/export/academic.theme.css, src/renderer/assets/themes/export/liber.theme.css
Some export theme style improvements, I rebase to latest marked.js and misc changes.
=> Misc style changes and marked

src/renderer/commands/index.js
| Fixed tickets    | #1619
.
---
fixes #1619
fixes #1620
=> Fix outdated export command

src/main/preferences/hunspell.js
Fix wrong condition.
--
Fixes #1637
=> Fix Hunspell dict installation

src/muya/lib/contentState/paragraphCtrl.js
| Fixed tickets    | #1621
Fixed horizontal line, table and types in blockquotes and lists.
---
fixes #1621
=> Fix allowed paragraph transformations

README.md
=> Documentation: Replace 'Is' with 'If' in 'If a version for your system unavailable'

README.md
=> [ci skip] Update spelling in readme

docs/i18n/zh_tw.md
Add Translation Traditional Chinese
--
=> Add Translation Traditional Chinese

src/renderer/spellchecker/index.js, test/unit/specs/extract-word.spec.js
Fixed bad regexp and optimize `extractWord` function performance.
=> Fix extractWord issue and optimization

src/common/filesystem/paths.js
=> Fix: #1696

src/renderer/components/sideBar/help.js
| Fixed tickets    | #1706
Fix settings button does not work.
=> Fix settings button does not work (#1706)

src/renderer/components/editorWithTabs/editor.vue
| Fixed tickets    | #1721
jumpClick can't jump to another file
=> Fix jumpClick can't jump to another file

src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/utils/turndownService.js
| Fixed tickets    | #1678 #1684 #1683 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1734)
=> fix some copy paste list bugs

src/muya/lib/utils/importMarkdown.js
| Fixed tickets    | #1735 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1739)
=> fix: empty blockquote issue

src/muya/lib/config/index.js, src/muya/lib/contentState/imageCtrl.js, src/muya/lib/utils/index.js
| Fixed tickets    | #1668 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1740)
=> fix: #1668 unexpect encode image url on windows

src/renderer/assets/styles/printService.css
| Fixed tickets    | #1670 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1732)
=> Fix mermaid diagram is not visiable when export html

package.json
release v0.16.0-rc.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1747)
=> release v0.16.0-rc.2

.github/PULL_REQUEST_TEMPLATE.md
| Bug fix?         | somewhat
| BC breaks?       | what does this mean
Using the template, the issue associated with a given pull request will now automatically close upon the PR getting merged. Also: the dist warninfpg was updated to fix a grammatical error.
You will now do “Fixes #[ticket number]”. For cases where multiple issues are closed, repeat the last sentence as necessary. If no tickets are fixed by the PR, put “none”.
--
=> pr template changes

src/muya/lib/contentState/copyCutCtrl.js
| Fixed tickets    | #1678 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1756)
=> fix #1678, copy task list should acording to the origin checked status

src/muya/lib/parser/marked/textRenderer.js
| Fixed tickets    | Fixes #1738 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1759)
=> fix export emoji in header

src/muya/lib/contentState/formatCtrl.js
| Fixed tickets    | Fixes #1749 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1760)
=> fix format tool can not work in table cell

src/muya/lib/contentState/inputCtrl.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1783)
=> Performance optimization of code block

src/muya/lib/ui/quickInsert/config.js
Change `table` shortcut `Cmd + T` to `Shift + Cmd + T`.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1800)
=> Update shortcut of table

docs/PORTABLE.md, docs/PREFERENCES.md
| BC breaks?       | yes
FIx some spelling errors in the documents. There may be more errors (
=> fix: spelling error

README.md
| Fixed tickets    | No
Update readme, add link to readme file translation of Traditional Chinese.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1818)
=> Update: link to readme translation of zh_tw

docs/PREFERENCES.md, src/main/preferences/schema.json, src/renderer/components/sideBar/toc.vue, src/renderer/prefComponents/general/index.vue, src/renderer/store/preferences.js, static/preference.json
| Fixed tickets    | Fixes #1772
word wrap in TOC
=> feat: word wrap in TOC

src/main/menu/actions/format.js, src/main/menu/actions/paragraph.js, src/muya/lib/contentState/formatCtrl.js, src/muya/lib/contentState/paragraphCtrl.js, src/renderer/store/editor.js
| Fixed tickets    | #1797
Refactor both selection IPC messages between renderer- and main process to improve performance and fix the linked bug.
---
fixes #1797
=> Refactor IPC selection messages

src/muya/lib/contentState/clickCtrl.js
| Fixed tickets    | Fixes #1698
fix bold or italic hyperlinks can't be opened through Cmd+Click
=> fix bold or italic hyperlinks can't be opened through Cmd+Click

.github/PULL_REQUEST_TEMPLATE.md
| Breaking changes?       | Now that I know what "BC changes" means, no.
| Fixed tickets    | non
Use plain English in PR template so people know what is being asked.
=> Rename 'BC changes' to something intelligable

src/common/filesystem/paths.js, src/renderer/commands/quickOpen.js, src/renderer/components/sideBar/search.vue, src/renderer/store/project.js
| Fixed tickets    | Fixes #1879 
Fixes Issue [https://github.com/marktext/marktext/issues/1879](https://github.com/marktext/marktext/issues/1879)
--
=> Fix #1879 Add .md extension to files created in sidebar if no extension is given

docs/PREFERENCES.md, src/main/preferences/schema.json, src/muya/lib/config/index.js, src/muya/lib/contentState/clickCtrl.js, src/muya/lib/contentState/updateCtrl.js, src/muya/lib/utils/cumputeCheckBoxStatus.js, src/muya/lib/utils/getParentCheckBox.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/editor/index.vue, src/renderer/prefComponents/general/index.vue, src/renderer/store/preferences.js, static/preference.json
| Fixed tickets    | #1724
Auto update others checked state while change a task
=> A task checked should update related task

src/muya/lib/contentState/inputCtrl.js
| Fixed tickets     | #1838
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1898)
=> fix: Math formula preview is not updated

src/muya/lib/contentState/inputCtrl.js
| Fixed tickets     | #1837 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1899)
=> fix: Issue with paragraph starting with three or more *

src/muya/lib/contentState/tableSelectCellsCtrl.js
| Fixed tickets     | #1825 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1900)
=> fix: Cannot destructure property row of i as it is null.

src/renderer/prefComponents/common/fontTextBox/index.vue
| Fixed tickets     | #1773 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1901)
=> fix: can not select Chinese font family name.

src/muya/lib/assets/styles/exportStyle.css, src/muya/lib/utils/exportHtml.js, src/renderer/components/editorWithTabs/editor.vue
| Fixed tickets     | #1523 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1902)
=> fix: export invalid math

src/muya/lib/contentState/clickCtrl.js, src/renderer/components/editorWithTabs/editor.vue
| Fixed tickets     | #1802 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1911)
=> fix: Editor jumps to last cursor if you toggle a task-list item

package.json
| Fixed tickets     | no
Release 0.16.0-rc.3
=> release version 0.16.0-rc.3

docs/LINUX.md
Update the AppImage part of installation doc for linux.
=> Update installation doc for linux

README.md
| Fixed tickets     | Fixes #1927
I update link to the projects page on github, it's good idea ?
=> fix #1927 : update roadmap link

src/main/preferences/schema.json
| Fixed tickets     | #1773 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1923)
=> fix regexp in schema file

src/muya/lib/assets/styles/index.css
Fixed ability to select inline math formulas but not the math preview.
=> Fix inline math selection

.travis.yml, src/renderer/contextMenu/editor/index.js, src/renderer/contextMenu/sideBar/index.js, src/renderer/contextMenu/tabs/index.js, src/renderer/prefComponents/spellchecker/index.vue, yarn.lock
| Fixed tickets     | #1915 
@fxha I found that electron change the argument of `menu.popup`  to an array, I didn't test whether it will affect other systems(Windows or Linux), so can you help test it?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1993)
=> fix context menu on macos

.github/CHANGELOG.md, README.md, docs/i18n/french.md, docs/i18n/ja.md, docs/i18n/ko.md, docs/i18n/pl.md, docs/i18n/pt.md, docs/i18n/spanish.md, docs/i18n/tr.md, docs/i18n/zh_cn.md, docs/i18n/zh_tw.md, package.json, resources/linux/marktext.appdata.xml
Release v0.16.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/2011)
=> Release v0.16.1

README.md
Describes Windows installation via Chocolatey
=> Include Chocolatey package installation option

README.md
Update the README to mention a distinguishing feature vs. other editors: pasting images from the clipboard and automatically saving them in a configurable folder.
=> Add ability to paste images to Features

.electron-vue/webpack.renderer.config.js
| Fixed tickets     | fixes #2088
Windows fix for Hunspell downloader; same as #1936.
=> Fix Hunspell dictionary downloader on Windows

src/muya/themes/default.css
| Fixed tickets     | resolves #1224
Dynamically change heading size according editor font size to improve editor scaling.
=> Improve heading font size scaling

electron-builder.yml
=> Reduce dependency bundle size

src/muya/lib/config/index.js, src/muya/lib/contentState/imageCtrl.js, src/muya/lib/parser/marked/renderer.js, src/muya/lib/ui/imageSelector/index.js, src/muya/lib/utils/getImageInfo.js, src/muya/lib/utils/index.js
| Fixed tickets     | fixes #1997, fixes #2001
This PR provides a fix for absolute images on Windows and also correct the autocomplete feature for images.
=> Fix image export issues on Windows

yarn.lock
Update `yarn.lock` file, because I can not install the dependences correctly with the old `yarn.lock` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/2178)
=> update: yarn.lock file

docs/KEYBINDINGS.md, src/main/keyboard/shortcutHandler.js, src/main/menu/index.js, src/renderer/pages/app.vue, src/renderer/store/editor.js
| Fixed tickets     | close #1953 
switch tabs using alt-<#num>
=> feat: switch tabs using alt-#num

src/muya/lib/contentState/copyCutCtrl.js
| Bug fix?          | yes/
| Fixed tickets     | fixes #1821
Fix unnecessary character sanitation on clipboard output.
=> Fix unnecessary character sanitation on clipboard output

src/renderer/commands/index.js
I decided to take a shot at it myself. There is a bug which causes the editor to be unfocused after changing the text direction, requiring a click with the mouse in the editor. If there's some easy way to fix that, that would be nice. This is my first time ever touching a vue project so I'm not sure where to even start debugging.
| Fixed tickets     | Fixes #2194
=> Support setting text direction via comand palette (#2194)

.github/CHANGELOG.md, README.md, docs/i18n/french.md, docs/i18n/ja.md, docs/i18n/ko.md, docs/i18n/pl.md, docs/i18n/pt.md, docs/i18n/spanish.md, docs/i18n/tr.md, docs/i18n/zh_cn.md, docs/i18n/zh_tw.md, package.json, resources/THIRD-PARTY-LICENSES.txt, resources/linux/marktext.appdata.xml, src/renderer/prefComponents/spellchecker/index.vue
Mark Text 0.16.2 bug fix release.
=> Release v0.16.2

docs/i18n/tr.md
| New feature?  | no
| Fixed tickets     | None
updated turkish translation of readme.md
=> updated turkish translation of readme.md

docs/i18n/tr.md
| Fixed tickets     | None
Apologies, looks like i messed up the image paths on tr.md, this fixes it
=> fix image paths on readme tr.md

src/muya/lib/contentState/tabCtrl.js
| Fixed tickets     | Fixes #2330
Enables users to use Shift+Tab for navigating tables in reverse.
=> fix: #2330 enable shift+tab for table navigation

src/muya/lib/selection/index.js
| Fixed tickets    | Fixes #520 
the y is 0 after press enter
=> fix: typewriter shake after press enter

src/main/menu/actions/window.js, src/renderer/commands/index.js
| Fixed tickets     | Fixes #2284
Added negative zoom feature.
=> Support negative zoom

src/main/menu/actions/file.js, src/renderer/contextMenu/editor/index.js, src/renderer/contextMenu/editor/menuItems.js, src/renderer/contextMenu/sideBar/menuItems.js, src/renderer/contextMenu/tabs/menuItems.js, src/renderer/prefComponents/spellchecker/index.vue
#2323 follow-up to fix three runtime crashes due to `Object.freeze` on mutable global fields.
=> Make global menu fields mutable

docs/i18n/ko.md
I updated ko.md (korean translation of README.md) to match the latest version of README.md
=> Updated korean translation of README.md

docs/i18n/zh_cn.md
Update Simplified Chinese translation of README to the latest version and polish a bit
=> Update Simplified Chinese translation of README

docs/IMAGES.md, src/main/preferences/schema.json, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/image/index.vue, src/renderer/store/preferences.js, src/renderer/util/fileSystem.js, src/renderer/util/index.js, static/preference.json
| Fixed tickets     | Fixes #549
This should be the last PR before v0.16.3 release which add support for the relative image directory.
NB: You need to build Mark Text to test this PR because the development version don't load images due to some permission issues.
=> Add support for relative image directory

README.md, docs/i18n/french.md, docs/i18n/ja.md, docs/i18n/ko.md, docs/i18n/pl.md, docs/i18n/pt.md, docs/i18n/spanish.md, docs/i18n/tr.md, docs/i18n/zh_cn.md, docs/i18n/zh_tw.md
| Fixed tickets     |
Fix error when installing using latest Homebrew in macOS. Just fix README and i18n files.
Here is screenshot:
=> Fix installation instructions in README.md

docs/FAQ.md
Slight clarification of the text in the FAQ menu. There was a bit more information in [this issue](https://github.com/marktext/marktext/issues/1286) than in the docs, so I added that, as well as a link from the preferences (see [this PR](https://github.com/marktext/marktext/pull/2692) )
| Fixed tickets     | Fixes #[1286](https://github.com/marktext/marktext/issues/1286)
---
See also [here](https://github.com/marktext/marktext/pull/2692) for update of preferences panel.
=> docs: Update "What is Aidou" in FAQ.md

docs/BASICS.md
| Bug fix?          | yes/no
Fix a typo
=> Fix a typo in BASICS.md

docs/EDITING.md
| Bug fix?          | yes/no
Fix a typo
=> Fix a typo in EDITING.md

README.md
Added winget to install options for windows
| New tests added?  | ot needed
Added winget to install options for windows
=> Add winget to install options for windows

docs/i18n/ko.md, docs/i18n/pt.md, docs/i18n/zh_cn.md, docs/i18n/zh_tw.md
Fix incorrect relative link from a md file under `src/i18n/`  to another.
=> docs: fix link from src/i18n/*.md to another

src/renderer/pages/preference.vue, src/renderer/prefComponents/common/bool/index.vue, src/renderer/prefComponents/common/compound/index.vue, src/renderer/prefComponents/common/titlebar.vue
| Bug fix?          | yes/no
@fxha This PR is very simple, just to fix some style confusion and some global style issues introduced in the last merged PR, I merged it directly.
=> fix: preference window style errors

.github/CHANGELOG.md, .github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, docs/i18n/french.md, docs/i18n/pl.md, docs/i18n/spanish.md, docs/i18n/tr.md, docs/i18n/zh_tw.md, test/specs/commonMark/commonmark.0.30.json, test/specs/commonMark/commonmark.0.30.md, test/specs/commonMark/compare.marked.md
change app name to MarkText, and update spec test results.
=> feat: change app name to MarkText and update spec test results

src/renderer/components/editorWithTabs/editor.vue, src/renderer/util/index.js
| Fixed tickets     | fixed #1775, fixes #2424, fixes #2591
Fixes the animated scroll behavior and some improvements with typewriter.
=> fix animated scrolling

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/main/menu/actions/file.js, src/renderer/components/sideBar/search.vue
Few changes after merging PRs and I added a note about the option to "like" (:+1:) issues to prevent the usage of +1 comments that we have to remove due to spam.
=> Code cleanup and improve issue templates

package.json, src/muya/lib/ui/fileIcons/index.js, src/renderer/components/sideBar/icon.vue, yarn.lock
=> fix: update file icons

src/muya/lib/contentState/inputCtrl.js
Just optimize the conditon of auto complement of markdown syntax.
=> feat: optimization of auto complement of markdown syntax

package.json, src/muya/lib/prism/loadLanguage.js, src/muya/lib/utils/importMarkdown.js, yarn.lock
| Fixed tickets     | Fixes #2854 
=> fix: #2854 codeblock highlight error

src/main/dataCenter/index.js, src/muya/lib/contentState/dragDropCtrl.js, src/muya/lib/contentState/pasteCtrl.js, src/muya/lib/ui/imageSelector/index.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/image/index.vue
Added the filename variable to relative image action too and fixed a few issues that may occur on bad input.
=> Add filename variable to relative image action

src/muya/lib/renderers/index.js, src/renderer/assets/styles/printService.css, yarn.lock
| Fixed tickets     | Fixes #2633 
=> fix: fix export mermaid pie chart error

src/renderer/components/sideBar/search.vue
Sidebar display abnormal when data is empty.
=> fix: fix sidebar display bug when data empty

src/main/exceptionHandler.js, src/main/index.js, src/main/menu/actions/file.js, src/main/preferences/index.js, src/main/windows/editor.js, src/renderer/bootstrap.js
Backport of a few issues that I found while trying out TypeScript in `src/main`.
=> Fix multiple JS issues

README.md
Add periods at the end of two sentences
=> Add periods at the end of sentences in README.md

README.md
Added periods and commas in README.md
=> Added periods and commas in README.md

src/muya/lib/ui/emojis/emojisJson.json
| Fixed tickets     | Fixes #2896 
Update emojis
=> opti: update emojis

.electron-vue/electron-builder/afterPack.js, electron-builder.yml, package.json
Bump version of develop branch and backport Linux binary fix.
=> Bump version to v0.17.0-rc1

src/muya/lib/contentState/codeBlockCtrl.js, src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/lib/utils/exportHtml.js, src/muya/lib/utils/index.js, src/renderer/util/pdf.js
| Fixed tickets     | Fixes #2936 
=> fix: escape html in code block

package.json
Merge "Bump version to v0.17.0-rc.2" on develop.
=> Bump version to v0.17.0-rc.2

test/unit/specs/match-electron-accelerator.spec.js
Fix unit tests for non-character keys.
=> Fix non-character key unit tests

src/muya/lib/parser/index.js
| Fixed tickets     | Fixes #2982
Prevent HTML rendering in preview mode if HTML rendering is disabled in settings. We allow the img tag to support our image resizer.
=> fix: prevent HTML rendering in preview mode

src/renderer/store/project.js
| Fixed tickets     | Fixes #3018
Not really a fix for #3018, but we'll improve the UX by performing more checks.
=> Check for same file before pasting

docs/LINUX.md
| Fixed tickets     | 
Added a description to get MarkText from the AUR to LINUX.md installation guide.
=> Added the AUR to LINUX.md installation guide

CONTRIBUTING.md, src/muya/lib/contentState/inputCtrl.js
| Fixed tickets     | Fixes #2959 #2534 
see issue
=> Update auto pair quote logic

src/muya/lib/contentState/pasteCtrl.js
| Fixed tickets     | Fixes #3067
Fixed #3067.
=> Fix image paste handler is not executed

.github/CHANGELOG.md, .github/workflows/release.yml, electron-builder.yml
Readd experimental Apple M1 support w/o any support.
=> Add experimental native support for Apple M1

src/main/dataCenter/index.js
=> Fix typo in the DataCenter class init method

src/muya/lib/assets/styles/index.css
| Fixed tickets     | Fixes #2353
- fixed multi line highlight.
=> Fixed multi line highlight.

docs/i18n/zh_tw.md
Update Traditional Chinese translation of README.
=> Update Traditional Chinese translation of README

src/main/app/index.js, src/renderer/store/project.js
| Fixed tickets     | Fixes #3150
Bug fix for the linked issue according https://github.com/electron/electron/issues/29598.
=> fix #3150: Win32 error in renderer process
