README.md
Webpack packs summary.gif into final app's bundle accidently.
When move summary.gif out of static/, the size changes: 75.4M -> 54.7M
=> fix: avoid pack summary.gif to app bundle

src/main/menus/help.js
The URL in the menu Help/Changelog pointed to a 404 page so I assumed that this URL should be the right one.
=> Fixed changelog URL

.github/CHANGELOG.md, src/renderer/components/titleBar.vue
| Fixed tickets    | #44 
This PR aims at fixing the wrong application menu offset on windows. It seems that the menu popup  parameters `x` and `y` are both offsets.
=> Set application menu offset without window position

src/main/actions/file.js, src/main/actions/marktext.js, src/main/utils.js
This PR adds a cross-platform solution of getting the home directory/path.
Maybe I should remove `getHomePath()` from `utils.js`, but I think it's better for later use.
=> Support of cross-platform home path

src/main/createWindow.js, src/main/index.js, src/main/utils.js, src/renderer/main.js
If the user drops a valid markdown file, a new windows is opened.
I added a to-do in `src/main/createWindow.js`. because the path should be verified before passing it to the parser.
=> Added drag & drop support for markdown files

src/editor/codeMirror/modes.js
I want swift syntax highlighting!
Code Mirror supports Swift syntax. so I added Swift to modes.js.
=> Add swift syntax highlighting

package.json
I suspect that the standard file association with txt/text files breaks the windows context menu for creating empty text files and just hides that option for whatever reason. Opening the files via "Open with..." does not create that behavior. As it is a Markdown Editor I suggest just removing that feature.
(Maybe startup time increased to but I am not sure about that.)
=> Temporary workaround for txt/text file associations

.travis.yml, package.json
Fix `npm run release` build failure if we build on OS's other than OSX.
We now have:
- `release`: builds Linux and Windows packages
- `release:all`:  builds Linux, macOS and Windows packages - works only on OSX!
- `release:linux`: ...
- `release:mac`: ... - works only on OSX!
- `release:win32`: ...
- `release:win64`: ...
@Jocs  You can only create `.dmg` on macOS or electron-build will throw exceptions.
=> Fix broken release configuration

package.json
| Fixed tickets    | #88
Now NSIS builder will build a single setup with x86 and x86_64 files.
Please can you refrain from force push to `master`. Thanks!
=> fix: #88 add windows x86 setup

src/main/createWindow.js, src/renderer/assets/window-controls.js, src/renderer/components/titleBar.vue
- enabled frameless window on Linux
- changed frameless window control icons and added restore icon
- enabled `windowStateKeeper`
- if window is out of bounds or `undefined` center window on screen
- fix problem where window is between two monitor (50% on first and on second monitor) if window has no frame on Linux
Before:
After:
=> enable frameless window on Linux

.github/CHANGELOG.md, src/main/actions/file.js, src/renderer/app.vue, src/renderer/components/editor.vue, src/renderer/store/editor.js
- Reset modification indicator after successfully saved changes
- If you want to exit with modifications and click on `Save`, the window will be closed
- Change quit message button text from `Delete` to `Exit and don't save`
@Jocs Should I open a issue for the TODO?
=> Reset modification indicator after successfully saved changes

.github/CHANGELOG.md, src/editor/contentState/index.js, src/editor/contentState/tabCtrl.js
`insertTab` code is a bugfix for #27, but not working correctly. At the moment tab focus is only disabled.
If you insert a tab or more than one space, it will get converted into one space. So a little problematic to insert 4 spaces after tab is pressed. At the moment tab code is commented out.
=> Disable tab focus and indent list items with tab

src/editor/index.js, src/editor/parser/parse.js, src/editor/utils/exportStyledHTML.js, src/renderer/components/sourceCode.vue, static/themes/dark.css, static/themes/light.css
This PR fixes hr and dark background style when export HTML, but still no PDF problems because PDF "prints" the browser content. Maybe use a node extension to export PDF with styled HTML content (in another PR)?
=> Fix hr and dark background style when export HTML

README.md
| Fixed tickets    | 150
The link to GFM originally pointed to CommonMark spec. Fixed the link to point to the GitHub Flavored Markdown Spec instead as it should be.
=> Fixed issue https://github.com/marktext/marktext/issues/150

doc/i18n/pl.md
| Fixed tickets    | 150
The link to GFM originally pointed to CommonMark spec. Fixed the link to point to the GitHub Flavored Markdown Spec instead as it should be.
=> Fixing issue https://github.com/marktext/marktext/issues/150

.github/CHANGELOG.md, src/main/actions/file.js, src/main/createWindow.js, src/renderer/store/editor.js
This fix is not very efficient because we copy the whole text and insert a single character, but node.js don't have such a feature.
@Jocs  Do you have any other ideas? Maybe we can replace the `markdown` string with another "high performance" string class later. I don't know js very well, but in c++ you can set spans, so you can ignore index 0 and work on remaining string and preallocated buffers etc, so you don't have to reallocated the string each time.
=> Fix UTF-8 BOM encoding

src/editor/codeMirror/modes.js
Added:
- c
- CMake
- Kotlin
- Nginx config.
- LaTeX
- reStructuredText
- PGP
Added alias for:
- go / golang
- sh / shell
I added a comment to `makefile` because CodeMirror doesn't support it and use `shell` as replacement.
=> Extend code block language support

src/main/menus/help.js
Disable update menu for snappy and not supported packages. Otherwise `Check for updates` will crash Mark Text, because it's not supported. macOS use the updater routine defined in `Mark Text` menu.
Supported packages are: macOS (dmg+zip), Windows (NSIS) and AppImage
=> Disable update menu for snap and not supported packages

.gitignore, build/windows/installer.nsh, package.json
| Fixed tickets    | #190
User can decide whether he wants to delete user settings (`marktext`) on uninstall. There are still two folders `marktext` and `Mark Text`, but `Mark Text` is used by NSIS setup.
=> fix: #190 Delete user settings on uninstall (NSIS)

.github/CHANGELOG.md, src/main/actions/edit.js, src/main/actions/file.js, src/main/config.js, src/main/createWindow.js, src/main/filesystem.js, src/main/menu.js, src/main/menus/edit.js, src/main/utils.js, src/renderer/app.vue, src/renderer/components/status.vue, src/renderer/notice/index.js, src/renderer/store/editor.js, src/renderer/store/index.js, src/renderer/store/notification.js, src/renderer/util/index.js, static/preference.md
=> Line ending

.github/CHANGELOG.md, src/editor/config.js, src/editor/contentState/codeBlockCtrl.js, src/editor/contentState/formatCtrl.js, src/editor/contentState/paragraphCtrl.js, src/editor/contentState/updateCtrl.js, src/editor/index.css, src/editor/parser/StateRender.js, src/editor/parser/marked.js, src/editor/utils/exportMarkdown.js, src/editor/utils/importMarkdown.js, static/themes/dark.css, static/themes/light.css
| Fixed tickets    | #220 
Mark Text support setext heading now. but the default heading style is still `atx`, and user can not change it.
Why we don't allow user to select heading style or code block style (fenced or indented) ?
Because setext heading only has `h1` and `h2`, and atx heading has `h1~6`.
fenced code block has language setting, but indented code block does not have.
So we set default heading is atx, and default code block style is fenced. and can not be changed.
--
=> feature: Support `setext` heading but the default heading style is `atx`

src/main/actions/format.js, src/main/actions/paragraph.js, src/main/actions/view.js, src/main/menus/edit.js, src/main/menus/format.js, src/main/menus/paragraph.js, src/main/menus/view.js, src/main/utils.js
| Bug fix?         | I think so
@Jocs `Upgrade Heading Level` in `main/actions/paragraph.js` should target `Upgrade Heading` because no item was labled so?
=> fix: get menu item by id

src/renderer/components/titleBar.vue
Fix an issue that you cannot drag the frameless window on the left side of the  title bar path.
=> Fix frameless window drag

.github/CHANGELOG.md, src/editor/contentState/index.js, src/editor/contentState/selectionCtrl.js, src/editor/index.js
| Fixed tickets    | #262
@Jocs How can I select a full block? `selection` helper seems not work ([ref](https://github.com/marktext/marktext/pull/273/files#diff-65dc429a509634687baabb2a50c9072cR11)).
=> fix: #262 select text from selected table cell only

src/main/config.js, src/main/menus/view.js, src/renderer/app.vue, src/renderer/components/editorWithTabs/index.vue, src/renderer/components/editorWithTabs/sourceCode.vue, src/renderer/components/sideBar/index.vue, src/renderer/components/titleBar.vue
Adjusted titlebar height to 25px on Linux and Windows, because of window-control icon size and improve toggle side-bar/tabs description.
=> Fix framless titlebar height

src/editor/contentState/updateCtrl.js
Only add a quote if it's not preceded by a letter or number.
=> bugfix: #351 smarter quotes auto pairing

src/renderer/contextMenu/sideBar/menuItems.js
| New feature?     |no
| Fixed tickets    | #365
In the sidebar folder browser, the context menu that's opened by right clicking on either a directory or file in the sidebar has a typo. The menu item for moving a directory or file to the trash is labeled "Move to Trach", when it should be labeled "Move to Trash".
Issue: https://github.com/marktext/marktext/issues/365
=> Bug #365 - Fix "move to trash" typo in sidebar menu

src/muya/lib/index.css, src/muya/themes/dark.css, src/muya/themes/light.css
| Fixed tickets    | #419 
Fix math inline preview text wrap error in #419.
Also improvement math preview styles in light and dark style. 
Please review.
=> Improvement math preview styles (#419)

src/muya/lib/contentState/updateCtrl.js
| Bug fix?         |  no
| Fixed tickets    | #414 
Add functional bracket auto-completion for good experience.
Please Review.
=> Improvement: #414 Add functional bracket auto-completion

.vscode/launch.json, src/main/app.js
| Fixed tickets    | #445 
Add vscode debugger config, you need install [Debugger for chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)
=> feature: vscode debug config support

src/renderer/index.css
| Fixed tickets    | #447
Fix removes hard line break from PDF export and Printing.
=> Exclude hard-line-break from printing.

src/renderer/components/titleBar.vue
| Fixed tickets    | no ticket
Fixing window resizing in north direction on top of title bar.
Added title-no-drag to left-toolbar for non darwin systems
=> fix: title bar resizing in north direction

src/main/actions/file.js
Fix the recommended filename because a markdown document without heading proposed a empty string.
=> fix: recommended filename can be empty

src/muya/lib/contentState/arrowCtrl.js
When the cursor is active and pressing up/down key in the table, the cursor should leave the table.
| Fixed tickets    | no ticket
When the user inside the table pressing the down/up key on the last/first row, that it should leave the table instead of jumping to the next/prev column.
**Behaviour before:**
**Behaviour after:**
=> Arrow key up/down navigation in a table

src/main/menus/help.js
| Fixed tickets    | no ticket
Help menu in OSX has two unnecessary separators because Electron doesn't support ```visible: false``` for separators [electron/issues/3494](https://github.com/electron/electron/issues/3494#issuecomment-231951984).
After fix, it looks:
=> fix: remove separators from help menu in OSX

src/main/utils/index.js
| Fixed tickets    | #481
Add missing dot to parse markdown files only. See #481 for more information.
=> fix: #481 add missing dot to parse markdown files only

.github/CHANGELOG.md, package.json, src/main/menus/help.js
| Fixed tickets    | #369
Added portable single executable Windows application (`Mark Text %version.exe`). The application still uses the default operating system application data storage path like `~/.config/martext/` on Linux.
=> Portable Windows application

.github/CHANGELOG.md, src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/uploadImage/index.vue, src/renderer/store/editor.js
| Fixed tickets    | #426 (partially)
Show a notification to copy the deletion URL of the uploaded image after the image was successfully uploaded.
=> opt: improve image upload UX

src/main/menus/edit.js, src/main/menus/paragraph.js, src/main/menus/view.js
| Bug fix?         | workaround
| Fixed tickets    | #523 - not fixed; just a workaround
This is a workaround for the `Ctrl+Alt` shortcut issue on Windows. As soon as electron release a fix for the issue, we need to revert the patch. The problem is that Chromium handle `Alt` and `AltGr` as `Alt+AltGr` since `v66` (electron `v3`) on Windows.
=> Workaround: Ctrl+Alt shortcut on Windows

.github/CHANGELOG.md, src/main/actions/view.js, src/main/app.js, src/main/menu.js, src/main/menus/file.js, src/main/window.js
| Fixed tickets    | #535
Please see #535 for more information.
@Jocs Can you please test it on macOS and do a code review? I need the patch for the [shortcut fixes](https://github.com/marktext/marktext/projects/6).
---
After merge: Open an issue for `FIXME` and `BUG`.
=> fix: #535 Application menu is not updated when switching windows 

.github/CHANGELOG.md, src/renderer/store/editor.js, src/renderer/store/help.js
| Fixed tickets    | #422
Please see #422. The PR also contains a bug fix for the blank document which was always saved as LF.
=> Don't show save dialog for an empty/not changed document

src/muya/lib/ui/formatPicker/index.css
The dark format box hover color and separator was not styled.
**Before:**
**After:**
=> Fix dark theme format box style

.github/CHANGELOG.md, appveyor.yml, package.json
- AppVeyor
- Publishing artifacts from AppVeyor to GitHub as draft release
- Removed duplicate `x86` build because we build 32-/64-Bit on the `x64` worker
- Updated cache directories
- Removed cross-platform support because of native dependencies
- Updated changelog from PR #555
I don't know why we can't set the `GH_TOKEN` variable via web interface but it is protected and only decrypted during `master` builds but not during PRs.
=> Publish artifacts to GitHub

src/main/config.js, src/main/exceptionHandler.js, src/main/index.js, src/main/utils/createGitHubIssue.js, src/renderer/main.js
- log all unhanded errors in main and renderer process
- possibility to report the error to GitHub (main process only)
@Jocs It it a problem when ` electron-unhandled` catches `unhandledRejection` error in the main process?
=> Add an exception handler

.electron-vue/webpack.main.config.js, .travis.yml, appveyor.yml, doc/RELEASE.md, package.json, src/main/cli.js, src/main/exceptionHandler.js
Add the last commit hash to the error handler report and `--version` command if not build by us. I also added a release guide.
@Jocs Do we need to add `brew` instructions?
=> Add last commit hash to error handler

src/muya/themes/dark.css
| Fixed tickets    | #587
Fix dark theme background color of preview boxes.
=> Fix dark preview box background color

src/main/actions/file.js
| Fixed tickets    | #583
Removed the background from the PDF document.
@Jocs Was there a reason for `printBackground: true` or because of a previous version with white/dark PDF style?
=> Remove PDF background color

src/main/actions/file.js, src/muya/lib/index.js, src/muya/lib/utils/exportHtml.js, src/muya/themes/dark.css, src/muya/themes/light.css, src/renderer/app.vue, src/renderer/assets/styles/printService.css, src/renderer/components/editorWithTabs/editor.vue, src/renderer/services/printService.js, src/renderer/store/editor.js
| Fixed tickets    | #583
- Revert #589 because we have to print the background; e.g. for code blocks
- fixes #583
- Remove print service container after exporting/printing
- Fixed an issue where you cannot print a document because of `undefined` HTML
- Use `win.webContents.print(...)` instead of `window.print()` to print the background
- `MarkdownPrint.print()` is now deprecated; find usages and delete it
**TODO's:**
=> Fix multiple print service bugs 

src/muya/lib/contentState/codeBlockCtrl.js, src/muya/lib/contentState/enterCtrl.js
| Fixed tickets    | #569
Please see #569 description. Additionally this PR updates the code block language when `enter` is pressed inside the language identifier text-box.
fixes #569
=> Prevent enter key as language identifier

package.json, src/renderer/components/sideBar/tree.vue
| Fixed tickets    | #604
This PR fixes the following build failure with the latest `vue` version:
```
Do not use v-for index as key on <transtion-group> children, this is the same as not using keys.
```
@Jocs I don't know why did you use a `key` there but I set it to another value.
fixes #604
=> Fix build failure with latest vue version

src/muya/lib/contentState/tabCtrl.js, test/e2e/specs/Launch.spec.js
| Bug fix?         | improvement
| Fixed tickets    | #564
Instead of selecting the whole cell and showing the context menu we move the cursor in the next cell at index 0. This allows us to tab through the table cells.
=> fix #564 move cursor in next table cell at index 0

.electron-vue/webpack.main.config.js, .electron-vue/webpack.renderer.config.js, .electron-vue/webpack.web.config.js, package.json, src/renderer/main.js
I added source map also for the production build to better reproduce errors reported by the new error handler. For the renderer we have to use `source-map-support` to map stack traces.
```
nosources-source-map - A SourceMap is created without the sourcesContent in it.
It can be used to map stack traces on the client without exposing all of the
source code. You can deploy the Source Map file to the webserver.
```
**Main error stack trace example:**
```
An unexpected error occurred in the main process
Error: Test
at ./build/linux-unpacked/resources/app.asar/dist/electron/webpack:/src/main/actions/file.js:338:9
at actions (./build/linux-unpacked/resources/app.asar/dist/electron/webpack:/src/main/menus/file.js:17:9)
at …
```
=> Add production source maps

package.json, resources/linux/marktext.desktop
XDG Desktop components will identify this program as a Markdown editor
| New tests added? |not needed
Linux desktops will identify MarkText as a markdown editor
=> Add Markdown MimeType

src/main/app.js, src/main/config.js
- Explicitly set `nodeIntegration` to `true` due to Electron 4 changes
- Prevent opening links and new windows by Electron (and our backend)
=> Explicitly define security guidelines

src/main/app.js, src/main/exceptionHandler.js, src/main/index.js, src/muya/lib/index.js, src/renderer/main.js
Backporting minor bug fixes from the experimental spellchecker branch.
- Allow opening directories via CLI
- Launch Chromiums crash handler to log process crashes (core dumps)
- Muya:
- Hide format box when right-clicking
- Update cursor position when right-clicking
=> backport: Spellchecker minor bug fixes

src/muya/lib/utils/exportHtml.js
| Fixed tickets    | #591
Fixed an error when exporting a code block without language identifier because the code block language may be empty or undefined.
fixes #591
=> Fix undefined language id when exporting a code block (#591)

.github/CHANGELOG.md, doc/i18n/zh_cn.md, package.json, resources/linux/marktext.desktop, src/main/actions/format.js, src/main/app.js, src/main/config.js, src/main/menus/format.js, src/main/shortcutHandler.js, src/muya/lib/assets/styles/index.css, src/muya/lib/config/index.js, src/muya/lib/contentState/formatCtrl.js, src/muya/lib/contentState/inputCtrl.js, src/muya/lib/ui/formatPicker/config.js, src/muya/lib/ui/formatPicker/index.css, src/muya/lib/ui/formatPicker/index.js, src/muya/lib/utils/domManipulate.js, src/muya/themes/dark.css, src/muya/themes/light.css
| Deprecations?    | yes - CmdOrCtrl-M altered to default inline_math, no longer minimises.
| New tests added? | no - not sure how to test, open to learning
Enables inline math with:
CmdOrCtrl-M
Inline Menu
Format dropdown menu
Also makes sure that formatting can be removed.
--
=> Add Inline Math to formatting menus

package.json, src/main/exceptionHandler.js, src/renderer/main.js, test/e2e/data/xss.md, test/e2e/specs/Launch.spec.js, test/e2e/specs/xss.spec.js, test/e2e/utils.js
- Added XSS end-to-end test
- Added native crash handler to the renderer process too
- Fixed a bug that Mark Text was not terminated when `MARKTEXT_EXIT_ON_ERROR` was set
- Fixed wrong error handler type information
=> Add XSS e2e test and fix error handler issue

.electron-vue/marktextEnvironment.js, .electron-vue/webpack.main.config.js, .electron-vue/webpack.renderer.config.js, src/main/cli.js, src/main/exceptionHandler.js, src/main/globalSetting.js, src/renderer/components/about/index.vue, src/renderer/store/index.js
I added the version information to the main and renderer process at compile time to simplify access and also outsourced the environment definitions.
=> Add compile time version information

src/main/preference.js, src/main/window.js, src/renderer/components/titleBar.vue, src/renderer/store/preferences.js, static/preference.md
| Fixed tickets    | #690
@Jocs Can you please test this on macOS? The default titlebar style is `CSD` with fallback on Linux and Windows to `custom`.
**Native:**
**CSD:**
macOS only
**Custom:**
fixes #690
/cc @fbruetting
=> User-defined titlebar settings

src/main/utils/index.js
The recommended filename/title was sometimes wrong because of wrong sorting.
=> Fix recommended filename/title

src/renderer/store/treeCtrl.js
| Fixed tickets    | #661 - only UI, not the upstream crash
Fixed wrong  path separator in tree view on Windows.
=> Fix Windows path separator in tree view

src/renderer/components/titleBar.vue
Fixed multiple exceptions during titlebar template initialization because `wordCount` is not defined.
=> Fix titlebar null property during initialization

src/renderer/store/project.js
| Fixed tickets    | #696
Fixed an issue with "open folder" that the editor was not initialized - no editor nor custom titlebar was shown. We now show an empty tab to initialize the editor.
=> Initialize editor when loading a folder and show default tab

src/renderer/components/editorWithTabs/sourceCode.vue
| Fixed tickets    | #606
@Jocs I think the issue exists because we don't listen for changes in source code mode but I'm unsure about it. This patch works and don't break other tab and sets the CodeMirror text when changes occur.
fixes #606
=> Fix tab change in source code mode

src/renderer/components/editorWithTabs/editor.vue
Fixed an exception when creating a new tab/loading a file because the old cursor (from the last tab) is used.
=> fix: tab switch exception due invalid cursor

src/renderer/components/editorWithTabs/sourceCode.vue
Fixed cursor position in source-code mode because the cursor is initial `null`.
No need to update changelog.
=> fix: set cursor in source code mode

.github/CHANGELOG.md, src/renderer/store/editor.js
Fixed an issue that relative images are not loaded after closing a tab.
=> fix: relative images are not loaded after closing a tab

.github/CHANGELOG.md, src/renderer/components/titleBar.vue
Hide titlebar control buttons in custom titlebar style.
=> Hide control buttions in fullscreen

src/main/exceptionHandler.js
Hide renderer errors in official binaries and only show one notification.
=> Hide renderer errors in official binaries

src/muya/lib/contentState/enterCtrl.js, src/muya/lib/contentState/updateCtrl.js, src/muya/lib/parser/marked/README.md, src/muya/lib/parser/marked/blockRules.js, src/muya/lib/parser/marked/lexer.js, src/muya/lib/parser/marked/parser.js, src/muya/lib/parser/marked/renderer.js, src/muya/lib/parser/render/renderBlock/renderContainerBlock.js, src/muya/lib/utils/exportMarkdown.js, src/muya/lib/utils/importMarkdown.js, test/unit/data/common/Blockquotes.md, test/unit/data/common/Lists.md, test/unit/data/gfm/Lists.md
Fixed CommonMark 264 and 265, allow `)` as ordered list delimiter and some small list (item) fixes.
> Changing the bullet or ordered list delimiter starts a new list:
> 
> ```
> - foo
> - bar
> + baz
> ```
>
> ```
> 1. foo
> 2. bar
> 3) baz
> ```
No need to update changelog because parser updates are already listed.
=> fix: update list item lexer and parser

src/muya/lib/index.js, src/muya/lib/selection/index.js
| Fixed tickets    | #813 
Fix the error that can not insert row and column when right click in table cell.
--
=> fix table context menu

.electron-vue/thirdPartyChecker.js, .travis.yml, LICENSE, appveyor.yml, package.json, resources/THIRD-PARTY-LICENSES.txt, src/renderer/components/about/index.vue, tools/generateThirdPartyLicense.js, tools/validateLicenses.js, yarn.lock
- Updated copyright holders
- Removed `build:web`
- Validate all production package licenses during CI
- Added third-party and Mark Text license to bundled binary
=> Update license and add third-party licenses

src/renderer/components/editorWithTabs/tabs.vue, src/renderer/components/titleBar.vue
Titlebar workaround for #339. BTW the tabs are not scrollable and the titlebar resizes to the tabs width if tab width `>` window width.
=> Titlebar workaround for #339

src/main/watcher.js
Only re-listen for files but not directories - fixed side bar on Linux when deleting files/directories.
=> fix: Linux rename syscall when using side bar

src/main/watcher.js
Improved RegEx and ignored all dotfiles. 
@Jocs Maybe we should ignore all other file extensions except markdown extensions.
=> Improve watcher RegEx

src/muya/lib/parser/marked/renderer.js, src/muya/lib/utils/exportHtml.js
| Fixed tickets    | #850
This change is not CommonMark/GFM compatible because they expect a bullet in front of the task box.
fixes #850
=> improve task list style

src/muya/lib/ui/emojiPicker/index.css
Fixed emoji picker icon color because the color was barely readable in dark themes.
=> fix: emoji picker icon color

src/muya/lib/contentState/paragraphCtrl.js
| Fixed tickets    | #848
@Jocs I think we should renderer with the old/last valid cursor position, right? This would apply for #799 as well.
=> fix: paragraphCtrl cursor may be null

.github/CHANGELOG.md, src/main/window.js, src/muya/lib/ui/emojis/index.js, src/renderer/assets/themes/one-dark.theme.css, src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/editorWithTabs/sourceCode.vue, src/renderer/components/editorWithTabs/tabs.vue, src/renderer/store/editor.js
| Fixed tickets    | #858
I guess I fixed #858 and found a few other issues:
- Fixed tab switching in source-code mode. Changes are not applied because the current tab is switched before changes are applied. I added the tab id to both `file-loaded` and `file-changed` events to set markdown content after switching tabs. NOTE: The tab id is only used in source code mode. `editor.vue`/muya uses `muya` as id and the source code mode workaround is not applied.
- Fixed source-code-/preview mode switching because source-code changes were not applied.
- Fixed exception because `checkEditEmoji` parameter was `null` 
- Free all vue events in `editor.vue` and `sourceCode.vue`
- A few One-Dark theme …
=> fix: source code mode tab switching

src/muya/lib/parser/parse.js, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/lib/parser/render/renderInlines/referenceLink.js
Fixed tickets    | #882
if tokens after `tokenizer` has reference link or reference image, no need to cache them. Because the `reference_definition` maybe removed later.
=> fix unecessary cache token

src/muya/lib/config/index.js, src/muya/lib/contentState/htmlBlock.js, src/muya/lib/contentState/paragraphCtrl.js, src/muya/lib/contentState/tableBlockCtrl.js, src/muya/lib/eventHandler/clickEvent.js, src/muya/lib/ui/baseFloat/index.css, src/muya/lib/utils/exportMarkdown.js
| Deprecations?    | html delete icon
| Fixed tickets    | #909 
Because I didn't set the code of html to `contentState.codeBlocks`, so it can not find the html code after duplicated.
--
=> Fix unable duplicate html and deprecate the html delete icon button

doc/SETTINGS.md, src/main/preference.js, src/muya/lib/index.js, src/muya/lib/utils/exportMarkdown.js, test/unit/specs/markdown-list-indentation.spec.js
| Fixed tickets    | #887
Fixed subsequent list paragraphs and removed `tab` indentation.
fixes #887
=> fix: subsequent list paragraphs

src/muya/lib/contentState/tabCtrl.js
| Fixed tickets    | #907 
if the word before the cursor is a HTML tag, auto complete raw html first, then if not, indent the list item.
--
=> fix list indent by tab

.gitignore, package.json, src/main/index.dev.js, src/main/menus/edit.js, src/muya/lib/contentState/backspaceCtrl.js, src/muya/lib/contentState/index.js, src/muya/lib/contentState/inputCtrl.js, src/muya/lib/contentState/paragraphCtrl.js, src/muya/lib/index.js, src/muya/lib/selection/index.js, src/renderer/components/editorWithTabs/editor.vue, yarn.lock
| Fixed tickets    | #934 #938 
1. rewrite selectAll in menu.
* if the cursor is in a cell, select all only select the full cell.
* if the cursor is in code block, only select the code block content.
* if the cursor is in language input, only select the language.
2. valid cursor, if the getCursorRange has invalid node, reset it to a valid cursor.
--
=> Fix remove content bug

src/muya/lib/config/index.js, src/muya/lib/parser/index.js, src/muya/lib/parser/marked/blockRules.js, src/muya/lib/parser/marked/inlineLexer.js, src/muya/lib/parser/marked/lexer.js, src/muya/lib/parser/marked/renderer.js, src/muya/lib/parser/rules.js, src/muya/lib/parser/utils.js, src/muya/lib/utils/importMarkdown.js, test/specs/commonMark/commonmark.0.29.json, test/specs/commonMark/commonmark.0.29.md, test/specs/commonMark/compare.marked.md
| Fixed tickets    | #958 
```md
markdown:
**<a href="**">
expect html
<p>**<a href="**"></p>
```
**Fixed commonmark examples:**
"example": 45,
"example": 46,
"example": 49,
"example": 51,
"example": 52,
"example": 65,
"example": 341,
"example": 353,
"example": 361,
"example": 367,
"example": 371,
"example": 379,
"example": 387,
"example": 391,
"example": 397,
"example": 399,
"example": 400,
"example": 475,
"example": 476,
"example": 479,
"example": 480,
"example": 520,
"example": 521,
"example": 522,
"example": 569,
"example": 572,
"example": 573,
"example": 581,
"example": 585,
Reduce the failed commonmark examples count from 126 to 97 now.
=> fix: commonmark example 475 and related failed examples

src/muya/lib/contentState/backspaceCtrl.js, src/muya/lib/contentState/clickCtrl.js
| Fixed tickets    | #613 
Because of Mark Text render immediately after click event. so can not canceled the selection.
--
=> fix: whole selection can not be canceled

src/main/app.js, src/muya/lib/parser/marked/lexer.js
| Fixed tickets    | #870 
Because we distinguish between task list and bullet list in Mark Text, the parsing here is somewhat different from the `commonmark Spec`, and the task list needs to be a separate list.
=> fix: #870 list parse error

.github/CHANGELOG.md, src/muya/lib/contentState/tabCtrl.js
| Fixed tickets    | #967 #334 
Support inline formats: 
```javascript
['strong', 'em', 'inline_code', 'image', 'link', 'reference_image', 'reference_link', 'emoji', 'del', 'html_tag', 'inline_math']
```
For example:
\*\*strong\<cursor\>**
after press `tab`
it becomes:
\*\*strong**\<cursor\>
--
=> feat: jump cursor to the end to format

.github/CHANGELOG.md, src/muya/lib/assets/styles/index.css
fix: #974
Change inline math vertical align to `top`.
=> fix: #974 inline math style optimization

src/muya/lib/assets/styles/index.css
=> fix: link style error

src/main/shortcutHandler.js
Fixes regression from PR #981 that not shortcuts and menus without id work anymore.
=> fix: shortcuts and menus without id not longer work

resources/linux/marktext.appdata.xml
Corrected wrong release date for Flathub page.
=> fix typo in flathub metadata

src/muya/themes/default.css, src/renderer/assets/themes/dark.theme.css, src/renderer/assets/themes/material-dark.theme.css, src/renderer/assets/themes/one-dark.theme.css, src/renderer/assets/themes/prismjs/one-dark.theme.css
Removed the code block background color from the source-code mode.
Regression PR #973
=> fix source-code background color

package.json, yarn.lock
Updated `vega-embed` to latest version.
[Test data](https://raw.githubusercontent.com/vega/vega/master/docs/examples/bar-chart.vg.json)
=> Update vega-embed to v4

src/renderer/config.js, src/renderer/util/theme.js
Added `Noto Color Emoji` as fallback emoji font on Linux to fix emojis. The user must have `Noto Color Emoji` preinstalled, otherwise the system emoji font is used. `Segoe UI Emoji` is used on Windows (10) and `Apple Color Emoji` on macOS.
=> add 'Noto Color Emoji' as default emoji fallback font on Linux

src/muya/lib/contentState/tabCtrl.js, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/lib/prism/index.js, src/muya/lib/prism/loadLanguage.js
now you can input language alias like `js`(javascript), `html`(markup).
and Mark Text will highlight it. like bellow:
\```js
const a = 'b'
\```
=> feat: support prism language alias

src/muya/lib/contentState/copyCutCtrl.js
| Fixed tickets    | #1046 
This issue due to muya did not degrade heading to paragraph when cut event.
=> fix: #1046

src/renderer/components/sideBar/toc.vue, src/renderer/util/listToTree.js
| Fixed tickets    | #966 
The TOC is expanded by default, and it is not possible to remember which nodes were expanded before. When the content is modified, the TOC will expand all.
=> fix: TOC level error

docs/PREFERENCE.md, src/main/menu/actions/file.js, src/main/menu/actions/theme.js, src/main/preferences/index.js, src/main/preferences/schema.json, src/renderer/prefComponents/general/index.vue, src/renderer/store/editor.js, src/renderer/store/preferences.js
| Fixed tickets    | #971
Implemented auto save with delay. There are still some issues with file changes on disk and auto save. With this PR we automatically load changes only if the file is saved, otherwise show a notification but the file on disk may be overwritten due further text editor changes.
@Jocs BTW I don't really know where to store `autoSaveTimers` because it's not UI relevant and I don't wanted to `commit` to make changes.
=> add: auto save with delay

src/muya/lib/contentState/inputCtrl.js, src/muya/lib/parser/index.js
1. write markdown bellow:
```md
中国
<Cursor>
```
2. Cursor just in another line, not a new paragraph. Write some other Chinese, The new characters will append to the end of first line, the second line removed.
=> fix: Enter multiple lines in Chinese

src/muya/lib/contentState/imageCtrl.js
The change event is not triggered when the image is deleted by the `delete` button。
=> fix: Delete image triggers muya change

src/renderer/components/titleBar.vue, test/e2e/specs/Launch.spec.js
| Fixed tickets    | #1123
Added `- Mark Text` to untitled tabs to remove the  redundant title but also to be more consistent to the title when a directory is opened (`filename - directory`). This applies to all OSs.
---
fixes #1123
=> Adjust titlebar title when using native window

src/muya/lib/contentState/paragraphCtrl.js
If the cursor is in math block, we can not create a new math block in the outer math block, we need to create a new math block after the previous math block.
--
=> fix: should not nest math block into other math block

src/muya/lib/contentState/enterCtrl.js, src/muya/lib/parser/render/renderBlock/renderContainerBlock.js
| Fixed tickets    | #1158 
Because the `#` and `.` will be recognized as id selector and class selector when render.
--
=> fix: #1158

src/muya/lib/contentState/copyCutCtrl.js
Because select text will not emit click event on mobile phone, so we didn't update the cursor after user select some text, So we need to get the current cursor range when we cut some text.
--
=> fix: cut not work on mobile devices

.github/CHANGELOG.md, appveyor.yml, docs/LINUX.md, docs/PORTABLE.md, package.json
Added Windows binary as ZIP-archive for both x86 and x64. We still need to test the automatically update feature for ZIP packages or disable this feature later.
=> Build Windows zip binaries

src/muya/lib/contentState/paragraphCtrl.js
Input Chinese like bellow：
press `backspace` key will delete all the content, but it's not the expected behavior. I only want to delete the last character.
--
=> fix: unexpected delete all content when input Chinese

src/muya/lib/index.js
Emit `crashed` event after editor is no longer editable.
--
=> emit crashed event when editor is no longer editable

src/muya/lib/contentState/clickCtrl.js
1. write some paragraphs.
2. put the cursor at the first paragraph.
3. click bellow the last paragraph.
--
=> fix: runtime error when click bellow the last paragraph

src/renderer/prefComponents/sideBar/config.js
Fix search `watch` key word will cause setting window became white screen.
--
=> fix white screen when search in setting window

package.json, yarn.lock
degrade vscode-ripgrep to v1.3.1 to test pass travis error.
=> Release 0.15.0

src/muya/lib/contentState/pasteCtrl.js
When copy from `Note` on macOS or from `weChat`, the paste html always contains full HTML document, but we only need the body content.
--
=> opti: optimization of paste

src/muya/lib/contentState/pasteCtrl.js, src/muya/lib/index.js, src/muya/lib/utils/importMarkdown.js, src/renderer/components/editorWithTabs/sourceCode.vue
| Fixed tickets    | #1226 
Also fix another issue, muya did not emit change event after paste action.
=> fix: #1226

package.json
| Fixed tickets    | #1164
This PR fixes issues with restricted execution permissions on Linux. All node modules will be unpacked during build and not at runtime. It should also improve startup time a bit.
=> Unpack all node modules during build

.travis.yml, appveyor.yml, package.json
This change should fix the wrong package filenames due an electron-builder breaking change.
**Tested on:**
=> Fix package filenames due electron-builder change

.travis.yml
The changes should fix Travis cache issues with the macOS build worker. Removing `vscode-ripgrep` and verify all dependencies takes some time but should fix the issue with failing builds.
=> Try to fix Travis CI cache issues

src/main/menu/templates/edit.js, src/main/menu/templates/file.js, src/main/menu/templates/format.js, src/main/menu/templates/help.js, src/main/menu/templates/paragraph.js, src/main/menu/templates/theme.js, src/main/menu/templates/view.js, src/main/menu/templates/window.js
| Fixed tickets    | #1254
Added ability to use the `alt` accelerator on Linux and Windows to open the menu.
=> fix: #1254 alt accelerator on Linux and Windows

src/main/utils/index.js
| Fixed tickets    | #1128
Fixed an exception in main process due invalid regex. `getRecommendTitleFromMarkdownString` should be replaced later by the top tree heading from the renderer process cache when requesting file save/export etc.
=>  fix: #1128 recommend title exception when heading contains spaces only

docs/KEYBINDINGS.md, src/main/keyboard/shortcutHandler.js, src/main/menu/index.js, src/renderer/pages/app.vue, src/renderer/store/editor.js
| Fixed tickets    | #1124
Added new shortcuts for tab management:
| Id                  | Default                                  | Description             |
| ------------------- | ---------------------------------------- | ----------------------- |
| `tabsCycle`         | <kbd>CmdOrCtrl</kbd>+<kbd>Tab</kbd>      | Cycle through tabs      |
| `tabsSwitchToLeft`  | <kbd>CmdOrCtrl</kbd>+<kbd>PageUp</kbd>   | Switch tab to the left  |
| `tabsSwitchToRight` | <kbd>CmdOrCtrl</kbd>+<kbd>PageDown</kbd> | Switch tab to the right |
---
resolves #1124
=> Cycle through tabs

src/muya/lib/contentState/pasteCtrl.js
if copy `https://fankui.shimo.im`, prevent it been parse as `[https://fankui.shimo.im](https://fankui.shimo.im)`,
--
=> Fix: prevent parse a url

.github/CHANGELOG.md, src/index.ejs, src/main/config.js, src/main/windows/setting.js, src/renderer/bootstrap.js, src/renderer/mixins/index.js, src/renderer/pages/app.vue, src/renderer/pages/preference.vue
Add loading page when init app.
=> Opti: add loading page when init page

src/muya/lib/assets/styles/index.css, src/muya/lib/config/index.js, src/muya/lib/parser/render/renderInlines/image.js, src/muya/lib/parser/render/renderInlines/loadImageAsync.js, src/muya/lib/utils/index.js
| Fixed tickets    | #1094 
Support inline image and show tools bar above image when the image is too small.
=> Feat: Support inline image and small image

src/renderer/config.js
| Fixed tickets    | #1299
This PR fixes #1299.
@Jocs Should we add `Noto Color Emoji` TTF font to Mark Text resource files? The only problem is that the font is 7,4MB large but we also ship ~60MB diagram libraries. I think we should outsource diagram libraries in extensions if available.
=> fix: #1299 add system emoji fallback fonts

src/muya/lib/contentState/enterCtrl.js
| Fixed tickets    | #1267 
1. Create the same check type(checked or not) when cursor in in previous task list item content.
2. Create unchecked task list item, when the cursor is at the end of task list item and press enter.
```md
```
will create checked task list item.
```md
```
if cursor at the end.
```md
```
will create unchecked task list item when press enter.
```md
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1372)
=> Fix: #1267

src/main/menu/actions/file.js, src/renderer/store/editor.js
| Fixed tickets    | #1349
Fixed wrong tab order by setting the tab filename/untitled tab number as recommended save dialog filename and set default path if root folder is opened.
resolved #1278
resolved #1349
=> fix: #1349 wrong save all tab order

src/main/app/index.js, src/main/filesystem/watcher.js, src/renderer/components/editorWithTabs/index.vue, src/renderer/components/editorWithTabs/notifications.vue, src/renderer/store/editor.js, src/renderer/store/help.js
| Bug fix?     | yes
File changed and removed notifications are now per-tab notifications and remain until the user interacts with it. I also fixed an issue that the history stack (last item here) was not added to the new file change.
=> Add per-tab notifications

.github/CHANGELOG.md, src/main/cli/index.js
| Fixed tickets    | #1382
Fixed wrong path concatenation.
=> fix: 1382 portable application data directory

src/muya/lib/parser/render/renderInlines/htmlTag.js, src/muya/lib/parser/utils.js
| Fixed tickets    | #1390
Because `dompurify` does not export `safety tags`, so use `sanitize(`<${tag}>`)` to judge whether the tag is safe. if it return empty string, it unsafe tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1393)
=> Fix: #1390 prevent XSS attact

.github/CHANGELOG.md, src/main/index.js
Workaround for #1359 to prevent drop shadow flickering and sometimes application flickering by temporary disabling GPU.
=> Workaround for #1359

.travis.yml, appveyor.yml, package.json
@Jocs  We should only push releases from the `release-*` branches?!
=> Update Travi CI distros

src/renderer/components/editorWithTabs/sourceCode.vue
| Fixed tickets    | #171
Please see code comment to this change. The change don't affect the source-code editor performance because it rendered all lines before too (`height: auto` was/is set on CodeMirror).
fixes #171
closes #791
=> Set CodeMirror viewport to infinity

package.json, src/main/app/index.js
| Fixed tickets    | #1244 
MacOS system also need to read file path from args, `open file` event only listen to `right click` file and select `open with`(open file by menu like bellow).
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1429)
=> Unable to open markdown file by command line

src/renderer/assets/styles/index.css
| Fixed tickets    | #1417 
Fix tooltip arrow styles.
Dear @fxha I've removed part of your code from 72702427f1465579cac2f6cffbe793b09b844cd2, I've found where it can breaks anything.
Tooltip by themes:
**Ulysses Light**
**One Dark**
**Material Dark**
**Graphite**
**Dark**
**Cadmium**
It also fixes an issue in Preferences.
Before fix:
=> fix: style error in tooltip arrow #1417

src/muya/lib/assets/styles/index.css
| Fixed tickets    | #1409 
Fix missed visual representation of **pre** tag
=> fix: pre tags rendering #1409

src/muya/lib/ui/frontMenu/index.css
| Fixed tickets    | no ticket
Front sub-menu has extra border and border-radius which is not fit to other menus.
Before:
After:
=> fix: ag front submenu is not corresponded to other menus

README.md, docs/i18n/french.md, docs/i18n/ja.md, docs/i18n/ko.md, docs/i18n/pl.md, docs/i18n/pt.md, docs/i18n/spanish.md, docs/i18n/tr.md, docs/i18n/zh_cn.md
| Bug fix?         | yes (typo in README.md)
| Fixed tickets    | N/A
The anchor to download section isn't linked properly. The link should use `#download-and-installation`, not `#download-and-install`.
--
=> Fix the download section anchor

src/main/app/index.js, src/main/app/windowManager.js, src/main/menu/actions/edit.js, src/main/menu/actions/format.js, src/main/menu/actions/paragraph.js, src/main/menu/actions/view.js, src/main/menu/index.js, src/main/menu/templates/edit.js, src/main/windows/editor.js, src/renderer/bootstrap.js, src/renderer/pages/app.vue, src/renderer/store/editor.js, src/renderer/store/layout.js, src/renderer/store/preferences.js
| BC breaks?       | yes
- Fixed multiple potential main process exceptions because the application menu may be `null`. E.g. when creating a new editor window and focusing the settings window.
- Fixed `windowId` type in renderer process
- Fixed line ending menu item state when switching tabs
- Breaking change: After creating a window the editor is either preview or source-code according settings but don't respect the last active editor window settings any more.
=> Fix application menu exceptions

src/renderer/components/editorWithTabs/editor.vue, test/e2e/specs/xss.spec.js
| Fixed tickets    | #1243
Allow 1x1, 1x2 and 2x1 tables.
---
resolves #1243
=> Allow 1x1, 1x2 and 2x1 tables

src/renderer/prefComponents/common/bool/index.vue
| Fixed tickets    | #1465 
Checkboxes in settings will use only the needed width.
=> fix: settings switch element used 100% of width

src/muya/lib/assets/styles/index.css
| Fixed tickets    | #1452 
Wrap long lines and adds padding for pre element
=> fix: wrap long lines and a little bit of padding for pre element

package.json, yarn.lock
Fixed build issue with optional dependency on Windows due to Electron 6/Node 12.
=> Fix build issue with optional dependency on Windows

src/main/windows/utils.js
Fixed invalid screen area on Windows because the screen area can be negative when primary display is on the right side.
=> Fix Windows screen area

src/muya/lib/eventHandler/keyboard.js, src/muya/lib/selection/index.js
| Fixed tickets    | #1460
Also fix bugs:
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1477)
=> Can not focus the first empty line in code block

.electron-vue/webpack.renderer.config.js, src/main/menu/actions/file.js, src/muya/lib/assets/styles/headerFooterStyle.css, src/muya/lib/config/index.js, src/muya/lib/index.js, src/muya/lib/utils/exportHtml.js, src/muya/lib/utils/index.js, src/renderer/assets/styles/printService.css, src/renderer/assets/themes/export/academic.theme.css, src/renderer/assets/themes/export/liber.theme.css, src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/editorWithTabs/index.vue, src/renderer/components/exportSettings/exportOptions.js, src/renderer/components/exportSettings/index.vue, src/renderer/pages/app.vue, src/renderer/prefComponents/common/textBox/index.vue, src/renderer/prefComponents/editor/index.vue, src/renderer/services/printService.js, src/renderer/store/editor.js, src/renderer/store/listenForMain.js, src/renderer/util/pdf.js
| Fixed tickets    | #349, #354, #1479
- Added export/print settings
- Added custom and user-defined themes for exporting/printing
- Fixed code block overflow in PDF
- Known issues:
- The blockquote border is rendered over header/footer when it's over multiple pages.
- Emojis may be black when exporting on Linux if `sans-serif` or `serif` is defined because the system fallback font is used instead colored emojis. `Noto Color Emoji` cannot overwrite this.
- Adding Noto Color Emoji to font fallback list result in files with multiple MB (because the font is included in PDF) and the emojis look weird due to the point above.
- Improvements: Print in another window for …
=> Export with options

.electron-vue/preinstall.js
=> Require Node.js >=12

src/muya/lib/assets/styles/exportStyle.css, src/muya/lib/parser/marked/lexer.js, src/muya/lib/parser/marked/parser.js, src/muya/lib/utils/exportHtml.js, src/renderer/assets/styles/printService.css, src/renderer/assets/themes/export/academic.theme.css, src/renderer/assets/themes/export/liber.theme.css, src/renderer/util/pdf.js
Adjusted export theme style and fixed bug that not content was shown.
Academic and Liber footnotes are almost the same:
@Jocs BTW there is a bug when using the pandoc example and switching between source- and preview editor multiple time, each time 4x spaces are added to the code block.
=> Adjust export theme style

package.json, yarn.lock
Update electron to version 7.0.1 and fix the `node-gyp` version to v6.0.1
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1599)
=> Update electron to v7.0.1 and resolve node-gyp to v6.0.1

src/renderer/commands/quickOpen.js, src/renderer/components/commandPalette/index.vue
| Fixed tickets    | #1607 
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1612)
=> Match keyword not only from the beginning #1607

src/muya/lib/config/index.js, src/muya/lib/contentState/codeBlockCtrl.js, src/muya/lib/eventHandler/resize.js, src/muya/lib/index.js, src/muya/lib/parser/render/renderBlock/renderContainerBlock.js, src/muya/lib/utils/resizeCodeLineNumber.js, src/renderer/prefComponents/editor/index.vue
| Bug fix?         | workaround
Temporary disable numbered code block lines due to #1648 to release first release candidate and allow application testing.
=> Temporary disable numbered code block lines due to #1648

src/renderer/spellchecker/dictionaryDownloader.js
Fix `Promise`/`await` issues and always ensure Hunspell dictionary before downloading.
=> Ensure Hunspell dictionary before downloading

src/renderer/assets/themes/one-dark.theme.css
Revert #1616 One-Dark color change because it's not compatible with One-Dark colors and was too bright.
=> Revert #1616 One-Dark color change

src/renderer/prefComponents/imageUploader/legalNoticesCheckbox.vue
The wording of this GDPR warning was not proper English, and a word was missing. This just cleans up that text to make it look more professional and polished.
=> Better phrasing of the GDPR warning

.travis.yml, appveyor.yml, electron-builder.yml
| Fixed tickets    | #1687, https://github.com/marktext/website/pull/15
Add deb/rpm packages to Linux and change default package file names.
**Known Issues:**
- License is shown as *proprietary* with both MIT and Expat on Debian packages (`deb`).
- Package name is shown as `marktext` instead `Mark Text`.
---
resolves #1687
=> Add deb/rpm and adjust package file names

src/muya/lib/assets/styles/index.css
| BC breaks?       | (what is this?)
| New tests added? | no
| Fixed tickets    | #1680
Stop rendering completed tasks as struck through; it was obscuring struck-through text entered by the user.
=> do not strike through completed tasks (#1680)

src/muya/lib/assets/styles/index.css
Forbid inline math overlay selection when selecting multiple lines.
=> Forbid inline math overlay selection

docs/PREFERENCES.md, src/main/preferences/schema.json, src/muya/lib/utils/exportHtml.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/markdown/config.js, src/renderer/prefComponents/markdown/index.vue, src/renderer/store/preferences.js, static/preference.json
| Fixed tickets    | #1628
Added an option to change the theme of the js-sequence-diagram diagrams. 
I didn't change the default theme to "simple" as suggested in the issue, I'll leave that to a maintainer. However, I do think that would be a good idea as the default "hand drawn" theme is absolutely atrocious.
I did notice some regressions in the diagram rendering that are **unrelated** to this change though. Namely, the diagram text is black even in dark themes, and the diagram gets horribly squished when exporting to both HTML and PDF. These issues did not exist in v0.15.1.
I've also …
=> Add setting for sequence diagram theme (#1628)

src/muya/lib/parser/render/renderInlines/htmlTag.js, src/muya/lib/utils/dompurify.js, src/muya/lib/utils/index.js, src/renderer/util/pdf.js
Fix dompurify warning when init Mark Text.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marktext/marktext/1781)
=> fix: dompurify warning when init app

src/muya/lib/parser/marked/lexer.js
| Fixed tickets    | #1733
Fixed wrong task list indentation in our custom marked.js implementation due to checkbox length.
=> fix: #1733 wrong task list indentation in parser

src/renderer/assets/themes/prismjs/dark.theme.css
In dark theme, variables become unrecognizable since they are white and same as plain text. For example in SQL language, the `AND` and `LIKE` look same as default text.
=> Variables shouldn't use same color as strings

docs/LINUX.md
The use of sudo for installations is neither necessary nor encouraged.
=> Remove sudo in flatpak installation instructions

src/muya/lib/assets/styles/index.css
| BC breaks?       | (what is this?)
| New tests added? | no
| Fixed tickets    | #1051
Long lines in code blocks are not wrapped; instead, a thin scroll bar is added when the content overflows.  This scroll bar appears regardless of the user's preference for hiding the scroll bars of the main content window.
=> Forbid line wrap in code blocks (#1051)

.github/PULL_REQUEST_TEMPLATE.md, .gitignore
| BC breaks?       | :shrug:
Fix .gitignore file to never allow dist files to be added and drop warning from PR that is cluttering up ever issue in the tracker.
=> Ignore dist files in repository, update PRtemplate

README.md
Just fix wrong flag emoji of zh_tw in README.md
=> Fix wrong flag emoji of zh_tw in README.md

docs/dev/BUILD.md
According to official information from https://github.com/nodejs/node-gyp
=> Update BUILD doc: node-gyp supports python 3

src/muya/lib/config/index.js, src/muya/lib/utils/exportHtml.js, src/renderer/assets/styles/printService.css
| Bug fix?          | yes (?)
Fixed image alignment in exported document according `data-align` attribute that is used by Mark Text. This is not a CommonMark/GFM compatible change!
=> Fix image alignment in exported document

docs/LINUX.md
The current link after `curl -L` downloads the HTML page for the file link on GitHub. I've updated the link to correctly download the raw file into the correct location(~/.local/share/applications).
=> Fix Desktop File link in curl command.

src/renderer/components/editorWithTabs/tabs.vue, src/renderer/components/sideBar/index.vue
| Bug fix?          | YES
| Fixed tickets     | No issues created for this bug yet
Hi maintainers, I'm sure u guys receive a lot more of issues than PR's, I just discover this app yesterday and I found it amazing, also I notice a little bug in the tabs, see below:
I'm not too much in this kinda tech, I'm more into php back-end, so that's my first time with Vue, I just find that away to solve the problem with events. Thx for the great docs Vue provide.
This PR pretend to fix a bug when the left bar is toggled
If u have anything I can improve, ur welcome!
=> Fix max width of editor tabs

src/main/keyboard/shortcutHandler.js
| Fixed tickets     | fixes #2117
Fixed an issue that multiple empty shortcuts are rejected by the validator.
=> Fix empty shortcuts in shortcut validator

src/main/preferences/schema.json
| Fixed tickets     | fixes #2121
Added missing encoding entry to the settings validator.
=> Add missing encoding entry

src/renderer/spellchecker/index.js
| Fixed tickets     | fixes #2015
Don't allow to set language detection to true on Windows because the feature is not implemented.
=> Fix Hunspell spell checker initialization on Windows

src/main/preferences/schema.json, src/renderer/prefComponents/general/index.vue, src/renderer/prefComponents/spellchecker/index.vue
- I removed the session option in settings  because it's not implemented.
- Language detection is no longer shown on Linux and Windows or when Hunspell is used.
- Added default settings values to `schema.json`.
=> Disable and hide unnecessary settings options

src/renderer/components/sideBar/treeFile.vue, src/renderer/components/sideBar/treeFolder.vue, src/renderer/components/sideBar/treeOpenedTab.vue
This pull request increases the indentation for each item in the sidebar project treeview. This improves readability and accessibility by making it easier to distinguish which file and folder belongs to which indentation level and consequently, which subfolder
The following image is what the sidepane tree looked like before:
And this is it now with the changes made
=> Increase indentation for sidebar treeview

src/muya/lib/parser/marked/inlineLexer.js, src/muya/lib/parser/marked/lexer.js, src/muya/lib/parser/marked/textRenderer.js
This PR fixes two issue when exporting documents:
- Fixed a crash in markedjs because `footnoteIdentifier` function was not implemented for inline renderer.
- Fixed issue that the footnote link reference was wrong.
=> Fix footnote renderer exception in markedjs

src/main/preferences/schema.json, src/muya/lib/config/index.js, src/muya/lib/contentState/codeBlockCtrl.js, src/muya/lib/contentState/containerCtrl.js, src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/contentState/paragraphCtrl.js, src/muya/lib/index.js, src/muya/lib/parser/marked/blockRules.js, src/muya/lib/parser/marked/lexer.js, src/muya/lib/parser/marked/options.js, src/muya/lib/prism/languages.json, src/muya/lib/utils/exportHtml.js, src/muya/lib/utils/exportMarkdown.js, src/muya/lib/utils/importMarkdown.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/markdown/index.vue, src/renderer/store/preferences.js, static/preference.json
| Breaking changes? | yes, but compatible
| Related tickets     | #954
This PR adds support for GitLab display math in code blocks. There are two open questions about settings and whether we should convert an existing code block (with text) into a GitLab math block (see TODO in code below). Currently there is a settings option to enable GitLab compatibility, that enables code block math support but we could also replace this options with a prefered display math style  (Mark Text or GitLab) and always render GitLab math like code blocks as display math.
<pre>
GitLab display math:
```math
1+1=2
```
</pre
=> Add GitLab math block support

src/muya/lib/utils/exportHtml.js
| Fixed tickets     | fixes #1142
Workaround for strange character encoding when exporting a document to PDF on macOS.
=> Fix bad font when exporting document on macOS

docs/KEYBINDINGS.md, src/main/keyboard/shortcutHandler.js, src/renderer/components/sideBar/search.vue
| Fixed tickets     | fixes #2040
Fix double used shortcut for search in folder and focus mode by using `Ctrl+Shift+J` to toggle focus mode. I also changed to "open folder" button when no folder is opened to be consistent to the other UI.
=> Fix double used shortcut

src/main/menu/templates/file.js, src/main/menu/templates/help.js, src/main/menu/templates/view.js, src/renderer/components/sideBar/search.vue, src/renderer/components/sideBar/tree.vue, src/renderer/prefComponents/editor/index.vue, src/renderer/prefComponents/general/index.vue, src/renderer/prefComponents/image/index.vue, src/renderer/prefComponents/imageUploader/index.vue, src/renderer/prefComponents/markdown/index.vue, src/renderer/prefComponents/sideBar/index.vue, src/renderer/prefComponents/spellchecker/index.vue, src/renderer/prefComponents/theme/index.vue
Following #2075, which revised grammar, the current request concerns use of punctuation in user strings, so that they follow conventions familiar for graphic interfaces.
Note that this request does include some further revision to grammar   (d791e529ff9c6e8bfd26ee7fe9a0cf85fe19f5d, d69622d65b7ba85ee16b79cf363171fffa99d775) not included revision to language not included in #2075.
The other changes are the following:
-    Remove full stops (.) trailing widget labels (f22308812a0875554f6f6e2bad557ef8a3a8c509, 4cb011d6fe955e450827127a01f01e7228acbd5d).
-    End with ellipsis ('...') for all menu entries that open windows or other applications (c713a1c424e8365f12457fbc00e153f44f80bcc0, 4cb011d6fe955e450827127a01f01e7228acbd5d).
-    Remove trailing colons (':'), which had appeared in the …
=> Conform user-interface text to conventions for trailing punctuation

README.md
The README translations section currently features two China/PRC flags, one pointing to zh_CN and one to zh_TW. I changed the Taiwanese translation to a Taiwan flag.
However I've heard that it's a bad idea to label the translations with flags in the first place, and that flags represent countries, not languages. One article is here: http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/
=> Edit README.md to label zh_TW translation with Taiwan flag

docs/MARKDOWN_SYNTAX.md
| Fixed tickets     | #2282
See #2282
=> Fix markdown syntax document mistake for table content align (#2282)

src/muya/lib/parser/rules.js
| Fixed tickets     | Fixes #2047
Just modify the regex of auto link rule.
=> Update regex of auto link to fix trailing slashes

docs/FAQ.md
Fixing link to portable page.
Link to Portable page is wrong in the wiki.
=> Update FAQ.md - link to Portable

src/renderer/components/editorWithTabs/tabs.vue
Closing tabs on mouse middle-click was added as a feature in #1282, where `click.middle` would pass `file` to `closeTab` as `tab`. In #1434, multiple functions including `closeTab` where changed to received `tabId` instead, but `click.middle`'s behavior was not modified to accommodate this change. 
What this means is that middle-clicking a tab to close it does not work in the current version of the app. This PR changes `click.middle` so it passes `file.id` instead of `file`, making middle-click work again.
=> Fix middle-click to close tab

src/muya/lib/prism/languages.json
| Fixed tickets     | 
Add codeblock highlight and coloration for the [SPARQL](https://www.w3.org/TR/sparql11-query/) and [Turtle](https://www.w3.org/TR/turtle/) languages (standard data format and query language for RDF knowledge graph). 
Those languages were already included in Prism languages, they have been added to the list in `src/muya/lib/prism/languages.json`
=> Add codeblock highlight and coloration for the SPARQL and Turtle languages

src/muya/lib/contentState/paragraphCtrl.js
Hi. I would like to contribute to your project.
This PR fixes #1933. 
cellBlock (sample data):
```json
{
"key": "ag-460",
"text": "",
"type": "td",
"editable": true,
"parent": "ag-457",
"preSibling": "ag-458",
"nextSibling": null,
"children": [
{
"key": "ag-461",
"text": "Text goes here",
"type": "span",
"editable": true,
"parent": "ag-460",
"preSibling": null,
"nextSibling": null,
"children": [],
"functionType": "cellContent"
}
],
"align": "",
"column": 1
}
```
=> fix: #1933 - Cannot copy table cell

src/muya/lib/ui/tablePicker/index.js
| Breaking changes? |no
| Fixed tickets     | Fixes #2383   
First row of table create grid was always highlighted.
Fixed by deleting code adding '.ag-table-picker-header' class to the first row of the grid. 
This may have been left in as a check during development.
After removal table creation behaves normally.
=> fix: #2383 Fixed table creation grid highlight issue

src/common/encoding.js, src/common/filesystem/paths.js, src/main/config.js, src/muya/lib/config/index.js, src/muya/lib/contentState/index.js, src/muya/lib/parser/render/renderBlock/renderToolBar.js, src/muya/lib/parser/utils.js, src/renderer/commands/quickOpen.js, src/renderer/config.js, src/renderer/contextMenu/editor/menuItems.js, src/renderer/contextMenu/sideBar/menuItems.js, src/renderer/contextMenu/tabs/menuItems.js, src/renderer/spellchecker/languageMap.js, test/specs/config.js
| New tests added?  | no
| Fixed tickets     | Fixes #2322
`QuickOpenCommand._getInclusions` was [accidentally mutating](https://github.com/marktext/marktext/pull/2323/files#diff-feaed7ea091ea671155a7b191cce00d9L180) the `MARKDOWN_INCLUSIONS` constant. So all subsequent searches were adding to the last set of inclusion patterns generated instead of making fresh ones. This made it unusable without restarting the application.
Once I fixed this, I wrapped `MARKDOWN_INCLUSIONS` and as many other objects that looked like they should be immutable with `Object.freeze()`.
This showed up a second accidental mutation of …
=> Fix quick open bug and freeze constants to avoid accidental mutation

src/muya/lib/prism/loadLanguage.js
| Fixed tickets     | Fixes #1752 
`stylus` is included in `pug`'s peerDependencies.
When we load `stylus`, it try to delete `Prism.languages.pug` reload dependent `pug`.
However, call `dynamic import` twice won't trigger the `IIFE` inside in `prismjs/components/prism-pug` twice.
As a result, the attribute `Prism.language.pug`  is missing after that.
=> fix: prism language missing while load dependent language (#1752)

src/renderer/assets/themes/graphite.theme.css, src/renderer/components/editorWithTabs/tabs.vue
Changed the color value of the word count color to be viewed against the sidebar in the graphite-light theme.
| Fixed tickets     | Fixes #2363
Fixed the color of the word counter in the graphite light theme so that it is viewable on the side bar.
=> Graphite light wordcount fix

src/main/menu/actions/file.js
Restrict save dialog file extensions to `.pdf` and `.html` when exporting a document.
=> Restrict export dialog file extensions

src/main/preferences/schema.json, src/renderer/spellchecker/index.js, src/renderer/spellchecker/languageMap.js
| Fixed tickets     | Fixes #2280
This PR allow BCP-47 language codes in spell checker to support some odd Windows languages like `en-029`. If you share your settings with another OS, the spell checker will eventually fail to load at start-up with an error message.
=> Allow BCP-47 language codes in spell checker

src/muya/lib/assets/styles/index.css
Changed footnote inline code font size from `14px` to default footnote font size.
=> Fix footnote inline code font size

docs/KEYBINDINGS.md, src/main/keyboard/shortcutHandler.js, src/main/menu/actions/view.js, src/main/menu/templates/view.js, src/renderer/store/layout.js
| Fixed tickets     | Fixes #1863 
Add shortcut `CmdOrCtrl + k` for 'toggle Toc'.
- If sidebar is hidden, will open sidebar and show the Toc
- If both sidebar and Toc are visible, Toc will be closed
- If sidebar is open but not Toc, will switch to Toc
=> feat: add shortcut for toggle-toc (#1863)

src/muya/lib/contentState/pasteCtrl.js
Fixed a bug that pasting had no effect when table cells where selected. We will replace the table cells text with the paste content, if only one cell is selected.
=> Replace text when only one table cell is selected

src/muya/lib/contentState/copyCutCtrl.js
Copy table cells text as plaintext if only one cell is selected, otherwise copy as markdown.
=> Allow to copy table cells text as plaintext

src/renderer/prefComponents/common/fontTextBox/index.vue
| Fixed tickets     | Fixes #1908
Fixed the linked issue that only one font was displayed. The reason was that `queryString` was initial the default font family and the whole list was filtered by that name. Now, we show the whole list for the default font or when an empty text is searched.
=> Fix font selection autocomplete

src/main/preferences/schema.json, src/muya/lib/config/index.js, src/muya/lib/contentState/pasteCtrl.js, src/muya/lib/parser/marked/options.js, src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/lib/utils/exportHtml.js, src/muya/lib/utils/index.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/markdown/index.vue, src/renderer/store/preferences.js, static/preference.json
Follow-up PR for #2360. This PR add the ability to disable HTML rendering in settings. For security reasons this settings option should be disabled by default and we should notify the user to enable this if we detect HTML. Currently this feature is enable by default!
For more security we should:
1. Disable HTML rendering by default and notify the user how to enable it, if needed.
2. Export the markdown document only in a separate and isolated window. If you bypass dompurify, you can still inject code via exporting - a quick and dirty workaround would be 3.
3. Fast verify the sanitized HTML and escape all HTML if the sanitized HTML looks suspicious.
=> Add option to disable HTML rendering

src/common/filesystem/index.js, src/common/filesystem/paths.js, src/main/app/index.js, src/main/filesystem/markdown.js, src/main/keyboard/shortcutHandler.js, src/main/menu/actions/edit.js, src/main/menu/actions/file.js, src/main/menu/index.js, src/main/utils/pandoc.js, src/main/windows/editor.js, src/renderer/components/exportSettings/index.vue, src/renderer/spellchecker/index.js
| Fixed tickets     | fixes #2373, fixes #2325, fixes #2355
1. Fixed file and directory detection on symbolic links.
2. Fixed an issue that the file list disappears when launching Mark Text with `--new-window`.
3. Fixed an issue that an empty editor was opened when you cancel the file selection dialog.
4. The PR should also fix #2355.
=> Fix symbolic links and related path issues

src/muya/lib/config/index.js
I disabled MathML in our sanitizer (remove all MathML elements) because DOMPurify had a few MathML exploits in the recent time and we don't use this feature. Also I made explicit that we want a string returned.
=> Disable MathML due to DOMPurify security issues

src/muya/lib/contentState/history.js, src/muya/lib/contentState/index.js
This is a workaround for #1321 until our new engine is complete.
> The current engine doesn't support a smart history and we need to store the whole state. Therefore, we push history only when the user stops typing. Pushing one pending entry allows us to commit the change before an undo action is triggered to partially solve #1321.
If the full text is already committed and the user removes one word and undo the action again, the last state is correctly restored:
1. Write `foo bar` and wait two seconds
2. Select `foo`, remove it and press `Ctrl+Z` in under two seconds
3. `foo` is restored
This workaround will fail if
- you don't wait two seconds to commit the history after typing `foo bar` …
=> Improve undo history

src/muya/lib/assets/styles/exportStyle.css, src/muya/lib/parser/marked/lexer.js, src/muya/lib/parser/marked/options.js, src/muya/lib/parser/marked/parser.js, src/muya/lib/parser/marked/renderer.js, src/muya/lib/parser/marked/slugger.js, src/muya/lib/parser/marked/urlify.js, src/muya/lib/utils/exportHtml.js, src/muya/lib/utils/importMarkdown.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/exportSettings/index.vue, src/renderer/prefComponents/common/bool/index.vue, src/renderer/util/pdf.js
| Fixed tickets     | #80
Basic TOC generator for the document exporter that I used for quite a time. Maybe we should refactor the code and integrate it into our marked.js fork?
**Example:**
=> Add TOC generator to document exporter

src/main/menu/actions/file.js
| Fixed tickets     | #2319
Revert attempt to fix #2355 in #2416 and add a proper fix because `href` is `null`.
Example: `[https://www.google.com]()` -> `href: null` but `text: https://www.google.com` where as `[https://www.google.de](https://www.google.com)` is `href: https://www.google.com` but `text: https://www.google.de`.
=> Fix unable to open URL

src/common/filesystem/paths.js
In the jsdoc comment for `isImageFile()`, 'true' is misspelled as 'ture'.  This pr simply fixes that.
Fixes the aforementioned typo in the documentation comment of one function.
=> Fix typo in `paths.js`

src/renderer/components/titleBar/index.vue
Fixes a typo in "Paragraph" for consistency with other elements in the counter toolip (Words, Characters, Paragraphs).
=> Fix a typo (Paragraphs instead of Paragraph) in the counter tooltip

docs/LINUX.md
Just a small suggestion to link "download the AppImage" in the first line of the Linux documentation to the place where you can actually download that file.
=> Docs: Add link pointing 'download the AppImage' to the latest release

package.json, yarn.lock
| Fixed tickets     | None
Bumps Electron version to 13, which enables native Wayland support (when run with `-enable-features=UseOzonePlatform --ozone-platform=wayland` flags)
=> chore(electron): bump to Electron 13

src/muya/lib/contentState/tabCtrl.js
fixes issue #2466 where shift-tab did not un-indent a list item
| Fixed tickets     | Fixes #2466 
Fixes issue of not being able to shift-tab to un-indent list item
=> fix: unable to un-indent a list item

src/renderer/prefComponents/general/index.vue
There are a lot of questions regarding [what is Aidou](https://github.com/marktext/marktext/issues/1286). There is a [little explanation in the FAQ](https://github.com/marktext/marktext/blob/develop/docs/FAQ.md#what-is-a-aidou-), so I added a 'more' link to that article on the preference.
| Fixed tickets     | Fixes #[1286](https://github.com/marktext/marktext/issues/1286)
---
See also [here](https://github.com/marktext/marktext/pull/2693) for clarification of docs.
=> add link to FAQ in Aidou preference

src/renderer/components/sideBar/search.vue
| Fixed tickets     | Fixes #1729 
When the side bar is created, calls the global search function if a word or phrase was selected to be searched for. It will now automatically perform the search through all files without the user having to press "enter" on the search bar
=> Search when invoked should get prefilled from the currently selected text #1729

src/main/menu/actions/file.js
| New tests added?  | no
| Fixed tickets     | Fixes #2396 
Local links to non-markdown files will open in the default application. 
Also checks that dirname has a value before joining it in pathname (was suggested in the discussion under this issue).
=> Open non-markdown files in default application #2396

src/main/menu/actions/file.js
| Fixed tickets     | Fixes #2489
`exists()` is an async function, therefore it returns a `Promise<boolean>` and must `await` / `.then()` it. `!(Promise<boolean>)` will always `false` since `Promise<boolean>` never goes `undefined` or `null`, so the checker will always prompt `The file "${path.basename(newPathname)}" already exists. Do you want to replace it?`, and the `true` branch will be never reached.
=> Fixed: `The file already exists` always pop up even that file doesn't exist.

docs/dev/BUILD.md
| Bug fix?          | yes (in documentation)
On Fedora and RHEL/CentOS, the package is spelled `libX11-devel`, with capital X.
Reference: https://pkgs.org/search/?q=libx11
I'm on Fedora 32, attempting `dnf install libx11-devel` didn't work, with capital X did.
On Debian-based distros, the convention for package names is all lowercase, but the installed library file is something like `/usr/lib/x86_64-linux-gnu/libX11.so.6`, and header files have capital X11 e.g. `/usr/include/X11/Xlib.h`, so informally calling it "libX11" is slightly more precise.
(Whereas libxkbfile is lowercase …
=> build instructions: Correct case for libX11

src/muya/lib/contentState/pasteCtrl.js
| Fixed tickets     | Fixes #2612
Fixed an issue that caused the paste handler to insert only HTML content because we set the wrong flag. All input was converted to HTML when both normal text and HTML was set in clipboard.
=> Fix wrong HTML escape in paste handler

src/muya/lib/parser/render/renderBlock/renderLeafBlock.js, src/muya/lib/parser/render/renderInlines/inlineMath.js, src/muya/lib/utils/exportHtml.js
| Fixed tickets     | Fixes #2301 
Adds support for mhchem in math blocks. Works by importing KaTeX mhchem extension after KaTeX.
=> Add mhchem support to math blocks

.electron-vue/dev-runner.js, electron-builder.yml
| Fixed tickets     | Closes #2435
Added an additional installer for macOS arm64 (Apple M1). This may breaks the existing update process on macOS but I'm unsure about it.
=> Enable macOS arm64 build target

.electron-vue/dev-runner.js, docs/dev/DEBUGGING.md, src/main/preferences/index.js
Preference migrations were always applied because `store.set` didn't remove old entries. I also updated the debugging docs and will upload the `node-profiler` for automatic profiling soon.
=> Fix preference migrations

src/muya/lib/parser/render/plantuml.js
Fix build again, replaced deprecated API and reduce PlantUML compression level to improve performance.
Edit: Why do we use Deflate when we could use Brotli with better compression but same performance?
=> Fix ESLint error and reduce PlantUML compression level

src/muya/lib/contentState/index.js, src/muya/lib/contentState/inputCtrl.js
| Fixed tickets     | Fixes #1854
Fixed the linked issue. The cursor may be in an invalid position because the underlying block was already removed. This was the case when selecting multiple blocks with the keyboard but not by mouse. In this case, we start a full render from the given start because the ending is unknown. It seems that the mouse selection doesn't update the cursor while selecting multiple blocks but the keyboard after each line.
=> Fix partialRender cursor if the block was already removed from state

src/main/config.js, src/main/windows/setting.js, src/renderer/prefComponents/common/compound/index.vue, src/renderer/prefComponents/editor/config.js, src/renderer/prefComponents/editor/index.vue, src/renderer/prefComponents/general/index.vue, src/renderer/prefComponents/image/index.vue, src/renderer/prefComponents/markdown/config.js, src/renderer/prefComponents/markdown/index.vue, src/renderer/prefComponents/sideBar/index.vue, src/renderer/prefComponents/spellchecker/index.vue, src/renderer/prefComponents/theme/index.vue
| Fixed tickets     | Fixes #2678, Closes #2105, Closes #2508
Fixed scaling issues on preference window by enabling scrolling and window-resizing. This PR also applies the UI improvements from @brainchild0 to the remaining settings. I've run out of ideas for the spelling and image tabs but please feel welcome to improve these. Another idea would be to highlight each settings entry inside a group and not like now, the whole block.
=> Fix preference scaling and improve UX

src/muya/lib/contentState/inputCtrl.js, src/renderer/components/editorWithTabs/sourceCode.vue, src/renderer/util/index.js
Fixed an issue that resulted in an Muya crash because the Codemirror selection was in the wrong order. This PR normalize the cursor position that  `anchor` (start) is always before `focus` (end).
**Example:**
1. Select text from bottom to top in source-code mode
2. Switch to normal editor
3. Click in the editor or just press backspace
4. A lot of exceptions
=> Normalize Codemirror cursor that start is always before end

src/main/keyboard/shortcutHandler.js
| Fixed tickets     | Fixes #2720 number (set to none if no tickets are fixed, repeat template for each ticket fixed)
Alt gr problem on other keyboard layouts
Use "Ctrl" on osx instead of "Alt"
=> fix: #2720 Alt gr problem on other keyboard layouts

src/muya/lib/parser/marked/blockRules.js, src/muya/lib/parser/marked/lexer.js, test/unit/specs/markdown-footnotes.spec.js
| Fixed tickets     | Fixes #2779
Fixed two Muya crashes that occurred while parsing markdown when...
1. ...a footnote didn't contain a space between footnote and text: `[^asd]:text`.
2. ...a footnote was escaped: `[^asd\]: text`.
The fixed behavior allows loose footnotes like `[^asd]:text`.
=> Fix markdown footnote parser

.github/workflows/build.yml, .github/workflows/release.yml, src/common/filesystem/index.js, src/main/preferences/hunspell.js
Try to fix CI on Windows by invalidating cache. I also reverted the synchronous path exists call from 478f1ca97a6208f334caa732cc9e30671cd3d800 because the API is used by the filesystem watcher.
=> Invalidate CI cache and use async path exists

docs/KEYBINDINGS.md, src/main/keyboard/shortcutHandler.js
| Fixed tickets     | Fixes none
Changes the default tab cycle keybinds from `CmdOrCtrl+...+Tab` to `Ctrl+...+Tab` (for cycle forward and backward) for expected behaviour on macOS.
On macOS, the keybind Cmd+Tab is used to cycle between windows (similar to Alt+Tab on Windows). Therefore, the default keybind of `CmdOrCtrl+Tab` is non-functional (as far as I can tell) on macOS as the window manager steals the key combination before Mark Text sees it. This PR changes the keybind to the expected out-of-the-box behaviour. I fixed this with `keybindings.json` for myself, but as this …
=> Do not use Cmd+Tab as a keybind on macOS.

.electron-vue/dev-runner.js, src/muya/lib/contentState/searchCtrl.js
| Fixed tickets     | Fixes 
- Support `$0` to present all the match.
-  Escape `$` inside the replacement; use look-behind to ignore escaped character (\$).
BTY, still not support `$10` which is greater than 9, @fxha do you is it necessary to support it?
=> fix: search group

src/muya/lib/contentState/tocCtrl.js
| Fixed tickets     | #2851 #2805
close #2851;
close #2805;
close #2570;
https://github.com/marktext/marktext/blob/4c517b163232af5649b7a26d4a5705e40bbe4817/src/muya/lib/contentState/tocCtrl.js#L10
the reason : this regex can't match the `U+00A0 No-Break Space (NBSP) Unicode Character`
e.g:
```js
const str1 = "## ss"
const str2 = "## ss"
console.log(str1.replace(/^ *#{1,6} {1,}/, '')) // ## ss
console.log(str2.replace(/^ *#{1,6} {1,}/, '')) // ss
console.log(str1.replace(/^\s*#{1,6}\s{1,}/, '')) // ss
console.log(str2.replace(/^\s*#{1,6}\s{1,}/, …
```
=> fix: toc update when modifying headers (fix #2851, fix #2805, fix #2570)

src/muya/themes/default.css, src/renderer/components/editorWithTabs/editor.vue, src/renderer/components/editorWithTabs/index.vue, src/renderer/components/editorWithTabs/tabs.vue, src/renderer/components/sideBar/index.vue
| Fixed tickets     | fixes #2019, fixes #2608
Fixed the editor overflow because the sidebar width was not added to the maximal width of the editor. I also changed the scrollbar cursor from text to default.
=> Fix editor overflow

src/renderer/util/index.js
| Fixed tickets     | Fixes #2541 Fixes #2470
close #2541;
close #2470;
https://github.com/marktext/marktext/blob/4c517b163232af5649b7a26d4a5705e40bbe4817/src/renderer/util/index.js#L151-L186
in `animatedScrollTo` fn, if the duration arg is 0 , the `easeInOutQuad` will always return NaN/-Infinity
```js
element.scrollTop = val // val NaN / -Infinity  equal  element.scrollTop = 0;
```
so the page will scroll from the page start(0) , cause the 'blink'.
=> fix: fix new line page scroll (fix #2541, fix #2470)

docs/PREFERENCES.md, src/main/preferences/schema.json, src/renderer/pages/app.vue, src/renderer/prefComponents/general/config.js, src/renderer/prefComponents/general/index.vue, src/renderer/store/editor.js, src/renderer/store/preferences.js, static/preference.json
Related to #1906
Adds a new setting to change the default zoom level under general settings.
=> Add zoom persistence

src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/imageUploader/index.vue, src/renderer/util/fileSystem.js
Multiple functions in `filesystem.js` didn't were `async` which lead to UB.
=> Fix async IO function in renderer

src/main/dataCenter/index.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/image/index.vue, src/renderer/store/preferences.js
| Fixed tickets     | Fixes #2809
| Fixed tickets     | Fixes #2126
| Fixed tickets     | Fixes #2559
You can now use `${filename}` in Preferences -> Image -> Local image folder
This is simply regex replaced with the current fileName.
I've only tested this on Linux but it should work on windows/mac.
=> Added support for image path variables (#2809)

src/muya/lib/parser/render/index.js, src/muya/lib/parser/render/snabbdom.js
| Fixed tickets     | #2836
close #2836;
https://github.com/marktext/marktext/blob/4c517b163232af5649b7a26d4a5705e40bbe4817/src/muya/lib/parser/render/index.js#L183
the reason: snabbdom `patch` fn doesn't parse SVGs correctly , Related issue [#388](https://github.com/snabbdom/snabbdom/issues/388), i had tried update snabbdom to version 2.1.0, but didn't work.
so we need to refresh the svg , use innerHTML.
```js
patch(oldVdom, newVdom)
const refreshSvgParent = (vDom) => {
if (vDom.children?.some(e => e.sel === 'svg')) {
const html = …
```
=> fix: #2836 fix formula first render

src/muya/lib/contentState/inputCtrl.js
| Fixed tickets     | Fixes #2269
Bug fix to append all soft-lines to the new block which were discarded before. See issue for more information.
=> fix: 2269 Append soft-lines on text removal

.github/workflows/build.yml, src/main/keyboard/shortcutHandler.js, src/main/windows/setting.js
Fixed invalid fallback accelerator warning in Electron shortcut handler and try to solve Windows CI failure by always installing dependencies.
=> Fix invalid fallback accelerator warning

src/main/menu/actions/file.js
| Fixed tickets     | Fixes #2731
This changes the default name set when saving an exported file, defaulting to the name of .md file. If not available, it then defaults to the first header. Previously, this order was reversed, with the header being defaulted to before the filename.
=> feat: set default name of exported file to current filename

CONTRIBUTING.md
[BUG]: outdated, missing, and/or broken links.
- The 'issue template' was linked to an old version. 
- 'JSDoc' was referenced, but not linked.
- Added a link to MarkText's 'issues' page for quick access in the "where should I start?" section. 
- Other: did some proofreading, edits, etc. to improve readability & appear more professional.
=> Fixes: grammar, spelling, readability + [BUG]

.github/workflows/release.yml
Downstream fix for https://github.com/microsoft/ripgrep-prebuilt/issues/15 to remove debug information from ripgrep on Linux.
- Size before ~40MB
- Normally/after: 5MB
=> Remove debug info from ripgrep [skip ci]

docs/IMAGES.md, src/renderer/components/editorWithTabs/editor.vue, src/renderer/prefComponents/image/components/folderSetting/index.vue, src/renderer/prefComponents/image/index.vue, src/renderer/util/fileSystem.js
- Relative images are now saved relative to the file if a variable is used.
- Fixed invalid relative image path when file and assets directory aren't on the save folder level.
----
fixes #2901
=> Fix invalid relative image path

.github/workflows/release.yml, electron-builder.yml
Fix same name for macOS arm64 and x64 setup.
=> Add architecture to artifact name on macOS [skip ci]

.electron-vue/postinstall.js, .github/workflows/release.yml, electron-builder.yml, package.json, yarn.lock
This should fix #2953, but the reason is still unknown. I guess that `electron-builder` has some bug that download the wrong architecture on macOS because the issue only occurs on release build script. For now, we rebuild all native libraries from source.
=> Fix prebuilt architecture on macOS

package.json, src/common/keybinding/index.js, src/main/menu/index.js, test/unit/specs/match-electron-accelerator.spec.js, yarn.lock
| Fixed tickets     | #2964
- Fix `Alt+F4` on Windows (https://github.com/electron/electron/issues/32674)
- Allow non-character key bindings ([see here](https://github.com/fxha/electron-localshortcut/commit/d32301bcbb2f1816c97941d81bb1bb0b9bdfef5b#diff-6d209b42d78478cc98ad988200eb8df96290c6ba8940efba664a830eaec8e3f0))
=> Fix non-character key bindings and Alt+F4 on Windows

src/main/menu/actions/file.js
| New feature?      |no
| Breaking changes? |/no
Description
Make sure that the filepath written to tab is the filepath that has processed the suffix name
When saving a new tag, the saved real filepath is inconsistent with the filepath written to the tab, resulting in two different tags of the same file
=> fix new tab filepath err

src/main/jsconfig.json, src/renderer/jsconfig.json, vetur.config.js
Fix code intellisense and Vetur by adding `jsconfig.js` for main and renderer.
I'm unsure about the target but it should be at least `es2020` because we build against node v16.
=> Fix code intellisense and Vetur

src/main/menu/actions/file.js, src/muya/lib/utils/markdownFile.js, src/muya/lib/utils/url.js
| Fixed tickets     | Fixes #3015
Fixed clickable HTML links (`<a href="C:\a.md">foo</a>`) on Windows because the `href` was filtered out by dompurify. This PR applies a patch to Muya to map paths like `C:\foo\bar\doc.md` to an UNC path `\\\\?\\C:\foo\bar\doc.md` on Windows that is allowed by the validator.
=> fix clickable HTML links on Windows (#3015)

.github/CHANGELOG.md, .github/workflows/release.yml, electron-builder.yml
Don't build macOS arm64 package because no one can install the built package.
See https://github.com/marktext/marktext/issues/2983#issuecomment-1031396465.
=> Remove macos arm64 package

docs/KEYBINDINGS_LINUX.md, docs/KEYBINDINGS_OSX.md, docs/KEYBINDINGS_WINDOWS.md, src/main/keyboard/keybindingsDarwin.js, src/main/keyboard/keybindingsLinux.js, src/main/keyboard/keybindingsWindows.js, src/renderer/commands/descriptions.js
| Breaking changes? | yes
| Fixed tickets     | Closes #3038
- Mapped upgrade heading to `Ctrl+Plus` (`+`) - this will work after updating packages due to a bug in key mapper.
- Added description for reload images shortcut in settings
Changes because we map `Ctrl+Shift+1` to the underlying character due to compatibility issues with non-US keyboards:
- Removed heading size shortcuts on Windows because we cannot bind any default keys that are static across all key board layouts
- Changed heading size accelerators on Linux to `Ctrl+Alt+Digit0-6`
A user on Windows have to manually set the key bindings above, but this should be no problem with the reworked settings.
=> Remove accelerator for heading size on Windows

package.json, src/main/menu/index.js, tools/deobfuscateStackTrace.js, yarn.lock
| Fixed tickets     | Fixes #3019
Add workaround for a post window shutdown exception that only occurs on macOS. Most likely due to the event loop queue.
=> fix-#3019: Workaround for post window shutdown exception

docs/FAQ.md, docs/dev/BUILD.md, src/main/filesystem/markdown.js, src/main/filesystem/watcher.js, src/main/menu/index.js, src/main/preferences/index.js, src/main/windows/editor.js, src/renderer/components/editorWithTabs/editor.vue, src/renderer/spellchecker/index.js
| Fixed tickets     | #3044
Ignore watcher event if file modification time doesn't changed and we marked the file as modified by the editor. I'll keep the issue open because there are still cases where the watcher normalization from chokidar fail, like when offline not change event is generated on a cloud drive.
=> Ignore watcher event if mtime doesn't changed

src/main/keyboard/shortcutHandler.js
| Fixed tickets     | Fixes #3074
Fix regression that an empty shortcut will crash main process.
=> Ignore empty key bindings

src/muya/lib/contentState/copyCutCtrl.js, src/muya/lib/contentState/deleteCtrl.js
| Fixed tickets     | Fixes #2816
Bug: The behavior of deleting the selected image was not fully implemented.
=> Fix: "delete" shortcut on a selected image deletes the text after it (#2816)

src/muya/lib/contentState/copyCutCtrl.js
| New tests added?  | no
| Fixed tickets     | Fixes #3068
Native applications do not cut or copy empty strings to the clipboard.  This makes us match that.  Benefit is if you tap cut twice by mistake you don't instalose your data:)
=> Don't copy (or on cut) empty data to the clipboard, matches native behavior

README.md, docs/i18n/ja.md, docs/i18n/ko.md, docs/i18n/pt.md, docs/i18n/tr.md, docs/i18n/zh_cn.md, docs/i18n/zh_tw.md, package.json, resources/linux/marktext.appdata.xml, src/main/menu/templates/help.js
This replaces marktext/marktext/pull/3349. It has the patch that @fxha asked me to apply in that PR. 
Domain name is being held hostage so URL no longer valid. See: #3348 and marktext/website#66
The domain [marktext.app](https://marktext.app/) is for sale, presumably no longer controlled by the devs on this project. This doesn't fix the bug. A menu item in the application still links to the bad URL. But I don't know how to fix that. Maybe there are other places it needs to be removed or changed.
=> Remove expired "marktext.app" domain
